Iterable/iterable-android-sdk

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
Fixed missing userID in request json.
=> Fix for missing userId param

iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppManager.java
Simple fix to remove the null check.
=> Fix for button click not working with an empty action.

iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableNotification.java
Updated the SDK to match the server-side payload passed down.
=> Updates attachment url location to pull from inside of the itbl payload.

iterableapi/src/main/java/com/iterable/iterableapi/IterablePushRegistration.java
Adds in additional error checking to not attempt to register without a valid registration object.
=> adds in additional error handling for registration

app/app.iml, app/build.gradle, build.gradle, gradle/wrapper/gradle-wrapper.properties, iterable-android-sdk.iml, iterableapi/build.gradle, iterableapi/iterableapi.iml, iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppManager.java
Updating gradle dependencies to target version 27
=> Itbl 4495 gradle updates

iterableapi/build.gradle, iterableapi/src/androidTest/java/com/iterable/iterableapi/IterableApiResponseTest.java, iterableapi/src/androidTest/java/com/iterable/iterableapi/IterableInAppTest.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableHelper.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableRequest.java
+ move to JUnit4 tests, improve retry logic.
=> [ITBL-4453] Handle response status codes, add onSuccess & onFailure callbacks

.travis.yml, iterableapi/src/androidTest/java/com/iterable/iterableapi/IterablePushRegistrationTest.java
* run token registration tests conditionally, when Google Play Services are present
=> [ITBL-4569] Set up Travis CI

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableAttributionInfo.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableDeeplinkManager.java, iterableapi/src/main/java/com/iterable/iterableapi/IterablePushActionReceiver.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableUtil.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java
Store attribution information for 24 hours after the last push open or deep link click
=> [ITBL-5290] Store attribution information

CHANGELOG.md, README.md
=> [ITBL-5303] Update documentation with recent SDK changes

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/test/java/com/iterable/iterableapi/IterablePushActionReceiverTest.java
... and the app is opened from a push notification.
Fixes #56
=> Fix a NullPointerException when SDK isn't initialized in Application#onCreate

iterableapi/build.gradle, iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableConfig.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableUtil.java, iterableapi/src/test/AndroidManifest.xml, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java
Device ID (autogenerated, persisted on first launch) - `deviceId`
App Package Name - `appPackageName`
App version - `appVersion`
App build number - `appBuild`
Iterable SDK version - `iterableSdkVersion`
=> [ITBL-5995] Store additional data in device fields

iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppHTMLNotification.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableInAppHTMLNotificationTest.java
=> [ITBL-6310] Fix NPEs when in-apps are resized after being dismissed

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableRequest.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java
Attempts to create a user profile when the userId is set.
=> Feature/itbl 6230 call create user for user 

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
=> [MOB-65] Catch all runtime exceptions that may happen in getAdvertisingIdInfo

README.md, iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppManager.java
=> [MOB-178] Add documentation for deferred deep linking

iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppMessage.java, iterableapi/src/test/resources/inapp_payload_multiple.json, iterableapi/src/test/resources/inapp_payload_single.json, iterableapi/src/test/resources/inapp_payload_single2.json, iterableapi/src/test/resources/inapp_payload_trigger_never.json
+  rename the field to customPayload
=> [MOB-212] Read in-app custom payload from the top level of the JSON object

iterableapi/build.gradle, iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableHelper.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppDisplayer.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppHTMLNotification.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppManager.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableInAppHTMLNotificationTest.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableInAppManagerSyncTest.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableInAppManagerTest.java, iterableapi/src/test/java/com/iterable/iterableapi/unit/TestRunner.java
Also, don't remove the schema when calling the click handler.
=> [MOB-291] Use action:// schema for custom actions, itbl:// for internal actions handled by the SDK

iterableapi/build.gradle, iterableapi/src/androidTest/java/com/iterable/iterableapi/IterableNotificationTest.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableFirebaseMessagingService.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppManager.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationBuilder.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationHelper.java, iterableapi/src/main/java/com/iterable/iterableapi/IterablePushActionReceiver.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableFirebaseMessagingServiceTest.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableNotificationTest.java
Also, extract static methods from IterableNotificationBuilder into IterableNotificationHelper to make them testable
=> [MOB-370] Make syncInApp package-private, rewrite a bunch of tests

iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppManager.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppMessage.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableInboxTest.java, iterableapi/src/test/resources/inapp_payload_inbox_multiple.json, iterableapi/src/test/resources/inapp_payload_inbox_show.json, iterableapi/src/test/resources/inapp_payload_inbox_update.json, iterableapi/src/test/resources/inapp_payload_inbox_update2.json
Add support for Inbox feature.
=> [MOB-234] Add support for Save to Inbox

BETA-TOS.md
=> Fixed capitalization

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFileStorage.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableInAppFileStorageTest.java
Also, trigger in-app queue update on app launch
=> [MOB-475] Fix in-app persistency

iterableapi-ui/src/main/java/com/iterable/iterableapi/ui/inbox/InboxFragment.java, iterableapi-ui/src/main/java/com/iterable/iterableapi/ui/inbox/InboxRecyclerViewAdapter.java, iterableapi-ui/src/main/java/com/iterable/iterableapi/ui/inbox/InboxRecyclerViewTouchHelper.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppDeleteActionType.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppDeleteSource.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppManager.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java
Changing method signature has a bit of ripple effect. Please check if the methods are called at appropriate places
=> [Mob-592] add in app deleted event

iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationBuilder.java
See https://developer.android.com/training/notify-user/expanded
=> [MOB-430] Show thumbnails in collapsed notifications

iterableapi-ui/src/main/java/com/iterable/iterableapi/ui/inbox/InboxFragment.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableInboxSession.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java
This is just step 1: adding the API call, `IterableInboxSession` class to hold data, and basic automatic tracking for the sessions. More will follow in upcoming PRs.
=> [MOB-635] Add basic tracking of inbox sessions

iterableapi-ui/src/main/res/layout/inbox_message_fragment.xml
Thanks for finding the bug @Ayyanchira!
=> [MOB-849] Replace ConstraintLayout with FrameLayout in Inbox UI

iterableapi/src/test/java/com/iterable/iterableapi/IterableInboxSessionTest.java
Checked the red lines in codecov and experimenting if it takes the code coverage of the file to 100%
=> [MOB-947] Adding test method for IterableInboxSession initializer

.travis.yml, app/build.gradle, app/src/androidTest/java/com/iterable/iterableapi/MainActivityTest.java, app/src/androidTest/java/com/iterable/iterableapi/testapp/InboxUITest.java, iterableapi-ui/build.gradle, tools/android-wait-for-emulator.sh
Also, fixes for existing UI tests.
=> [MOB-959] Run UI tests on CI and report coverage

iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppDisplayer.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppHTMLNotification.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppManager.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableInAppHTMLNotificationTest.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableInAppManagerTest.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableInboxTest.java
Added new public method incorporating inAppLocation. Previous public methods now route to the new one with in-app as a default parameter to location.
=> [MOB-965] Bug Fix inApp location not being sent properly

iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFileStorage.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableInAppFileStorageTest.java
Implementing fileoperation queue with delay of 0.1 sec to perform the operation and avoid repeated save calls
=> Make In App Save Asynchronous

iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppHTMLNotification.java
Added IterableInAppLocation to IterableWebViewClient class.
Hardcoded location is removed and is now the location stored in IterableInAppHTMLNotification.
=> [MOB 1060] SessionID for inapp clicks while in inbox

app/src/androidTest/java/com/iterable/iterableapi/MainActivityTest.java
Added a test method to check if swipe delete removes the item from the list after refreshing the activity.
Added comments to work on for next test day.
=> [MOB - 1129] Add UI test for swipe delete

iterableapi-ui/src/main/java/com/iterable/iterableapi/ui/inbox/IterableInboxActivity.java, iterableapi-ui/src/main/java/com/iterable/iterableapi/ui/inbox/IterableInboxFragment.java
Passing layout id through the activity + more javadocs + make some methods protected
=> [MOB-1003] More changes for Inbox customization

iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppDisplayer.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableWebView.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableWebViewClient.java
It's not the default rendering method yet, but very close to being ready.
=> [MOB-961] Implement in-app rendering with DialogFragment

iterableapi/src/androidTest/java/com/iterable/iterableapi/IterableNotificationTest.java
Cherrypicking #183 to the master branch.
=> [MOB-1189] Backport the fix for a failing test

iterableapi/src/main/java/com/iterable/iterableapi/IterableFirebaseMessagingService.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationHelper.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableFirebaseMessagingServiceTest.java, iterableapi/src/test/resources/push_payload_ghost_push.json
=> [MOB-1187] Add isGhostPush method for apps to detect ghost/silent pushes

iterableapi-ui/src/main/java/com/iterable/iterableapi/ui/inbox/IterableInboxAdapter.java, iterableapi-ui/src/main/java/com/iterable/iterableapi/ui/inbox/IterableInboxDateMapper.java, iterableapi-ui/src/main/java/com/iterable/iterableapi/ui/inbox/IterableInboxFragment.java
Mirroring iOS functionality here.
=> [MOB-1225] Add DateMapper interface to Inbox

README.md
- Cleaned up the Mobile Inbox section to point to support docs
- Updated the installation instructions
- Added note about AndroidX dependency
=> Updates to README for Mobile Inbox

iterableapi-ui/src/main/java/com/iterable/iterableapi/ui/inbox/IterableInboxFragment.java
Adding Check to see if the fragment is destroyed for configuration changes.
=> [MOB-1227] Bug Fix - Remove redundant trackInboxSession

iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppDisplayer.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java
static Notification updated on creation. Retained insetPadding.
=> [MOB-1193] - Maintain DialogFragment consistency on rotation

iterableapi/src/test/java/com/iterable/iterableapi/IterableInAppManagerTest.java
Two test methods for Dialog and Dialog Fragments for their expected behaviors.
=> [MOB-1281] - Test method to see if inapp are sustained

iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppHTMLNotification.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableWebView.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableWebViewClient.java
Hiding and showing in-app before resizing to avoid animation effect.
=> [MOB-1192] Remove animation from Dialog Fragment startup

app/build.gradle, app/src/androidTest/AndroidManifest.xml, app/src/androidTest/java/com/iterable/iterableapi/IterableInternal.kt, app/src/androidTest/java/com/iterable/iterableapi/tests/InboxCustomizationTest.kt, app/src/androidTest/java/com/iterable/iterableapi/util/DataManager.kt, app/src/androidTest/java/com/iterable/iterableapi/util/PathBasedStaticDispatcher.kt, app/src/main/assets/filter-by-message-type-messages.json, app/src/main/assets/inbox-with-additional-fields-messages.json, app/src/main/assets/inbox-with-custom-cell-messages.json, app/src/main/assets/inbox-with-multiple-cell-types-messages.json, app/src/main/assets/simple-inbox-messages.json, app/src/main/res/layout/additional_fields_cell.xml, build.gradle
Also, add support for Kotlin Espresso tests.
=> [MOB-1130] Add tests for Inbox customization

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java
Add mergeNestedObject parameter to updateUser method signature. Also keeping the old one passing false as default.
=> [MOB-1625]-updateUser API-Add mergeNestedObject

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/main/java/com/iterable/iterableapi/IterablePushRegistration.java, iterableapi/src/test/java/com/iterable/iterableapi/IterablePushRegistrationTest.java
Adding methods to add custom device attributes, remove device attributes. Integrated it with existing push registration and test methods.
=> [MOB-1482] Add Device Attributes methods

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppManager.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableInAppManagerSyncTest.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableInAppManagerTest.java
Make sure we clear the in-app queue immediately on logout.
=> [MOB-1788] Clear in-app messages on logout

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
Important change to avoid breaks for customers using this feature
=> [MOB-1916] - updateEmail fix backward compatibility

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
changing parameter name to deviceToken in docs
=> updating broken parameter names

README.md
=> Adding a link to the Beta Mobile SDK Disclaimer

iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppManager.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppMessage.java
If a message is consume type, remove the message only after click events on in-app OR if pressed BACK_BUTTON.
=> [MOB-1876] - Consume a message after click/back

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableAuthManager.java
Doesn't call login logic if the auth token has not changed
=> Fixed the check for string equality by DT

iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java
1. Using IterableConstants to define background Animation duration
2. Modularized the code for background animation and reused for showing and hiding background
=> [MOB-2264] - Parallel Background Animation

iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java
=> [MOB-2338] Add safety checks before dismissing the in-app dialog

iterableapi/src/main/java/com/iterable/iterableapi/IterableRequest.java, iterableapi/src/main/java/com/iterable/iterableapi/OfflineRequestProcessor.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiRequestTest.java
1. Added from JSON and toJSON to IterableApiRequest class.
2. Added temporary task schedular code in offline request processor to see if it can form the request from the database
=> [MOB-2150] - Request Serialization

iterableapi/src/main/java/com/iterable/iterableapi/IterableTask.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableTaskManager.java, iterableapi/src/main/java/com/iterable/iterableapi/OfflineRequestProcessor.java, iterableapi/src/main/java/com/iterable/iterableapi/OnlineRequestProcessor.java
Fixing Android Studio warnings, unused variables, fixed parameters in SQL queries, etc.
=> [MOB-2421] Cleanup IterableTaskManager

.github/pull_request_template.md
=> [MOB-2368] - Template for PRs

iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableRequestTask.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableTaskRunner.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableTaskStorage.java, iterableapi/src/main/java/com/iterable/iterableapi/OfflineRequestProcessor.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableTaskRunnerTest.java, iterableapi/src/test/java/com/iterable/iterableapi/TaskSchedulerTest.java
* [MOB-2372](https://iterable.atlassian.net/browse/MOB-2372)
Part 2 of MOB-2372. Implements `IterableTaskRunner` that doesn't detect network yet, but runs in a background thread and executes all requests directly.
For next steps, needs: 
* callback handling (unless we only send requests that don't need callbacks)
* network detection
=> [MOB-2372][2] Implement IterableTaskRunner

iterableapi/src/main/java/com/iterable/iterableapi/IterableTaskRunner.java, iterableapi/src/main/java/com/iterable/iterableapi/OfflineRequestProcessor.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableTaskRunnerTest.java, iterableapi/src/test/java/com/iterable/iterableapi/TaskSchedulerTest.java
* [MOB-2373](https://iterable.atlassian.net/browse/MOB-2373)
Call original request callbacks when a task is completed.
=> [MOB-2373] Call request callbacks on task completion

iterableapi/src/main/java/com/iterable/iterableapi/OfflineRequestProcessor.java, iterableapi/src/test/java/com/iterable/iterableapi/OfflineRequestProcessorTest.java
https://iterable.atlassian.net/browse/MOB-2446
1. Added hashset of strings for all offline api
2. Passing request to task schedular only if requests are there in hashset
3. added a constructor for testing purpose.
4. Added test method to check if api's are handled correctly
=> [MOB-2446] - Online vs Offline handling

iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java
https://iterable.atlassian.net/browse/MOB-2285
1. Added systemVersion to getMessageApi json
2. Added test assertion to check if systemVersion is passed
=> [MOB-2285] - Add OS version to getMessagesAPI

iterableapi/src/main/java/com/iterable/iterableapi/IterableTaskRunner.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableTaskRunnerTest.java
* [MOB-2435](https://iterable.atlassian.net/browse/MOB-2435)
Add logic to handle retriable errors and reschedule processing with a set interval (60 seconds) whenever they happen.
=> [MOB-2435] Offline mode: handle network errors

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java
https://iterable.atlassian.net/browse/MOB-2531
1. Storing offline feature flag to shared preference.
2. Loading offlineconfiguration from shared preference during initialization. Default set to false. If nothing in shared preference, it will be false again.
=> [MOB-2531] - Persist offline configuration

iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppManager.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppMessage.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiAuthTests.java, iterableapi/src/test/resources/inapp_payload_multiple.json
* [MOB-2456](https://iterable.atlassian.net/browse/MOB-2456)
Adds support for the sorting of the in-app queue by priority
=> [MOB-2456] in-app priority support

iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java
https://iterable.atlassian.net/browse/MOB-2545
Change constant string value from sentAt to Sent-At
=> [MOB-2545] - Change sentAt header param to Sent-At

iterableapi/src/androidTest/java/com/iterable/iterableapi/IterableApiRequestsTest.java, iterableapi/src/main/java/com/iterable/iterableapi/OnlineRequestProcessor.java
https://iterable.atlassian.net/browse/MOB-2549
Added createdAt field in Online Request Processor. Thus now all the requests will have `createdAt` timestamp in them.
=> [MOB-2549] - createdAt in all the request

CHANGELOG.md, iterableapi-ui/build.gradle, iterableapi/build.gradle, sample-apps/inbox-customization/app/build.gradle
* [MOB-2510](https://iterable.atlassian.net/browse/MOB-2510)
Prepare for 3.2.10 release. This one won't be shipped from `master`. After merging the PR, I'll cherry-pick it onto an earlier commit and make a tag/release from that.
=> [MOB-2510] Prepare for 3.2.10

app/build.gradle, build.gradle, iterableapi-ui/build.gradle, iterableapi/src/androidTest/java/com/iterable/iterableapi/IterableApiResponseTest.java
Update Gradle, Android Gradle Plugin, Kotlin and resolve a few deprecation warnings.
=> [MOB-2391] Update Gradle plugins

CHANGELOG.md, iterableapi-ui/build.gradle, iterableapi/build.gradle, sample-apps/inbox-customization/app/build.gradle
https://iterable.atlassian.net/browse/MOB-2554
Releasing 3.3.0-beta1
=> Prepare for 3.3.0-beta1

.github/workflows/build.yml, build.gradle, iterableapi-ui/build.gradle, iterableapi/build.gradle
* [MOB-2615](https://iterable.atlassian.net/browse/MOB-2615)
Enable Kotlin support and add Kotlin runtime as a dependency.
=> [MOB-2615] Enable Kotlin plugin, add Kotlin stdlib as a dependency

.gitignore, build.gradle, gradle.properties, iterableapi-ui/build.gradle, iterableapi/build.gradle, maven-push.gradle
https://iterable.atlassian.net/browse/MOB-2579
1. Added maven-push.gradle which does the essential job of generating POM files and signing and uploading.
NOTE: This assumes that developer now has GPG key, password and location of the file store in local.properties. Refer here: http://sorcersoft.org/project/site/gradle/userguide/signing_plugin.html
2. Updated existing gradle file to include maven-push as a part of its tasks
3. gradle.properties now has common variables across api and api-ui project
4. Gitignore changes to not include pom files generated
=> [MOB-2579] - Maven Push essentials

CHANGELOG.md, iterableapi-ui/build.gradle, iterableapi/build.gradle, iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppManager.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppMessage.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiAuthTests.java, iterableapi/src/test/resources/inapp_payload_multiple.json, sample-apps/inbox-customization/app/build.gradle
* [MOB-2774](https://iterable.atlassian.net/browse/MOB-2774)
* This PR contains all the changes needed for the release of the Android SDK version 3.2.13.
=> [MOB-2774] SDK version 3.2.13 release

iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppManager.java
* [MOB-2882](https://iterable.atlassian.net/browse/MOB-2882)
* adds back in the read state check while processing in-apps
=> [MOB-2882] add back in read state check

.gitignore, CHANGELOG.md, build.gradle, gradle.properties, iterableapi-ui/build.gradle, iterableapi/build.gradle, maven-push.gradle, sample-apps/inbox-customization/app/build.gradle
* [MOB-2890](https://iterable.atlassian.net/browse/MOB-2890)
* fixes read state with messages (already merged into the base branch of this PR, `stable`)
* brings in maven deployment requirements
* prepares for version 3.2.14 release
=> [MOB-2890] SDK version 3.2.14

CHANGELOG.md, README.md, iterableapi-ui/build.gradle, iterableapi/build.gradle, iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java, sample-apps/inbox-customization/app/build.gradle
* [MOB-2965](https://iterable.atlassian.net/browse/MOB-2965)
* changes to prepare the SDK for the release of 3.3.0
=> [MOB-2965] version 3.3.0

iterableapi/src/androidTest/java/com/iterable/iterableapi/IterableApiRequestsTest.java, iterableapi/src/main/java/com/iterable/iterableapi/CommerceItem.java
* [MOB-2922](https://iterable.atlassian.net/browse/MOB-2922)
* adding more fields to `CommerceItem`
=> [MOB-2922] trackpurchase API

CHANGELOG.md
https://iterable.atlassian.net/browse/MOB-2991
Updated the CHANGELOG
=> [MOB-2991] Android SDK, version 3.3.1 - CHANGELOG

CHANGELOG.md, iterableapi-ui/build.gradle, iterableapi/build.gradle, sample-apps/inbox-customization/app/build.gradle
* [MOB-2991](https://iterable.atlassian.net/browse/MOB-2991)
* updating version SDK
=> [MOB-2991] update version numbers

iterableapi/src/androidTest/java/com/iterable/iterableapi/IterableNotificationTest.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationHelper.java
https://iterable.atlassian.net/browse/MOB-2976
1. Removed the code which set the when time to 0. This disabled our notification to have timestamp.
=> [MOB - 2976] - Adding time stamp to notification

CHANGELOG.md
=> Preparing for 3.3.1

CHANGELOG.md, iterableapi-ui/build.gradle, iterableapi/build.gradle
https://iterable.atlassian.net/browse/MOB-3025
Preparing for 3.3.2
=> Mob 3025 version 3.3.2

sample-apps/inbox-customization/app/build.gradle
* [JIRA-XXXX](https://iterable.atlassian.net/browse/JIRA-XXXX)
=> Updating sample app version

iterableapi/src/androidTest/java/com/iterable/iterableapi/IterableApiDeeplinkTest.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java
https://iterable.atlassian.net/browse/MOB-3087
1. Removed  failing method which are purely checking backend redirection logic.
2. In IterableApiTest.java, updated the expected string to what it is currently returning. which is "http://iterable.com"
=> [MOB - 3087] - Remove link redirection test

iterableapi/src/androidTest/java/com/iterable/iterableapi/IterableApiRequestsTest.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java
* [MOB-3142](https://iterable.atlassian.net/browse/MOB-3142)
* The updateCart API added to the SDK
=> [MOB-3142] add updateCart API and tests

iterableapi/src/androidTest/java/com/iterable/iterableapi/IterableApiRequestsTest.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java
* [MOB-3142](https://iterable.atlassian.net/browse/MOB-3142)
* removes the top level `dataFields` from `updateCart` (not actually present in the API)
=> [MOB-3142] remove top level dataFields

CHANGELOG.md, iterableapi-ui/build.gradle, iterableapi/build.gradle, sample-apps/inbox-customization/app/build.gradle
https://iterable.atlassian.net/browse/MOB-3165
Preparing for 3.3.3
=> Prepare for 3.3.3

iterableapi/src/androidTest/java/com/iterable/iterableapi/IterableApiRequestsTest.java, iterableapi/src/main/java/com/iterable/iterableapi/CommerceItem.java
* [MOB-3181](https://iterable.atlassian.net/browse/MOB-3181)
* add `dataFields` to `CommerceItem`
=> [MOB-3181] add dataFields to CommerceItem

CHANGELOG.md, iterableapi-ui/build.gradle, iterableapi/build.gradle, sample-apps/inbox-customization/app/build.gradle
* [MOB-3263](https://iterable.atlassian.net/browse/MOB-3263)
* update patch numbers and changelog for version 3.3.4
=> [MOB-3263] version 3.3.4 changelog and numbers

CHANGELOG.md, iterableapi-ui/build.gradle, iterableapi/build.gradle, sample-apps/inbox-customization/app/build.gradle
https://iterable.atlassian.net/browse/MOB-3415
Preparing for 3.3.6
=> Prepare for 3.3.6

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
* N/A
* slight refactor and additional comments before i do my next PR
* no functional changes
=> Slight Refactor

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java
* [MOB-3673](https://iterable.atlassian.net/browse/MOB-3673)
* allows `clickedUrl` inside `trackInAppClose` to be `null`
=> [MOB-3673] allow clickedUrl to be null in trackInAppClose

iterableapi/src/main/java/com/iterable/iterableapi/IterablePushActionReceiver.java
https://iterable.atlassian.net/browse/MOB-3472
Closing system dialog is not supported Android 12 onwards resulting into crashes. Hence removing the line
fixes #385
=> [MOB-3472] - Remove code which closes system dialog

iterableapi/src/main/java/com/iterable/iterableapi/InboxSessionManager.java
* [MOB-3709](https://iterable.atlassian.net/browse/MOB-3709)
* encapsulates what's getting tracked, same as on iOS
=> [MOB-3709] adds function to inbox session manager

CHANGELOG.md, iterableapi-ui/build.gradle, iterableapi/build.gradle, sample-apps/inbox-customization/app/build.gradle
https://iterable.atlassian.net/browse/MOB-XXXX)](https://iterable.atlassian.net/browse/MOB-3741
Releasing 3.3.9
=> [MOB - 3741] - Prepare for 3.3.9

iterableapi/src/main/java/com/iterable/iterableapi/IterableWebView.java
* [MOB-3768](https://iterable.atlassian.net/browse/MOB-3768)
* explicitly removes file access from `IterableWebView.java`
=> [MOB-3768] block unnecessary access for in-app functionality

CHANGELOG.md, iterableapi-ui/build.gradle, iterableapi/build.gradle, sample-apps/inbox-customization/app/build.gradle
* [MOB-3872](https://iterable.atlassian.net/browse/MOB-3872)
> Preparing to release 3.4.1
=> Prepare for 3.4.1

CHANGELOG.md, iterableapi-ui/build.gradle, iterableapi/build.gradle, sample-apps/inbox-customization/app/build.gradle
* [MOB-3911](https://iterable.atlassian.net/browse/MOB-3911)
Release 3.4.2
=> [MOB-3911] Prepare for 3.4.2

iterableapi/src/main/java/com/iterable/iterableapi/ImpressionData.java, iterableapi/src/main/java/com/iterable/iterableapi/InboxSessionManager.java
* [MOB-3873](https://iterable.atlassian.net/browse/MOB-3873)
This pull requests updates the session tracking functions to allow for the proper aggregation of message impressions when the user scrolls through the message list.
=> [MOB-3873] message impression aggregation fix

CHANGELOG.md, iterableapi-ui/build.gradle, iterableapi/build.gradle, sample-apps/inbox-customization/app/build.gradle
* [MOB-4107](https://iterable.atlassian.net/browse/MOB-4107)
Prepare for 3.4.3
=> Prepare for 3.4.3

app/src/androidTest/java/com/iterable/iterableapi/MainActivityTest.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableWebChromeClient.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableWebView.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableWebViewClient.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableInAppManagerTest.java
* [MOB-3892](https://iterable.atlassian.net/browse/MOB-3892)
* fixes the collapsed height caused by javascript disabling implementation
=> [MOB-3892] in-app top layout fix

CHANGELOG.md, iterableapi-ui/build.gradle, iterableapi/build.gradle, sample-apps/inbox-customization/app/build.gradle
* [MOB-4190](https://iterable.atlassian.net/browse/MOB-4190)
* version 3.4.4 release patch
=> [MOB-4190] version 3.4.4

iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java
* [MOB-4025](https://iterable.atlassian.net/browse/MOB-4025)
* refactoring after MOB-3892
=> [MOB-4025] in-app top layout fix refactor

iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableWebView.java
* [MOB-4263](https://iterable.atlassian.net/browse/MOB-4263)
* uses `onDraw` rather than `onPreDraw` to get the size of in-apps
=> [MOB-4263] use load data with base URL due to platform change

CHANGELOG.md, iterableapi-ui/build.gradle, iterableapi/build.gradle, sample-apps/inbox-customization/app/build.gradle
* [MOB-4298](https://iterable.atlassian.net/browse/MOB-4298)
* updates Android SDK to version 3.4.5
=> [MOB-4298] update SDK to version 3.4.5

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
* [MOB-4266](https://iterable.atlassian.net/browse/MOB-4266)
> Making trackPushOpen public
=> [MOB-4266] - Make trackPushOpen Public

CHANGELOG.md, iterableapi-ui/build.gradle, iterableapi/build.gradle, sample-apps/inbox-customization/app/build.gradle
* [MOB-4463](https://iterable.atlassian.net/browse/MOB-4463)
Prepare for 3.4.6
=> Prepare for 3.4.6

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java
* [MOB-4535](https://iterable.atlassian.net/browse/MOB-4535)
* reorganizes the login and logout flow to match the structure and naming on iOS
* allow `setEmail` and `setUserId` to additionally pass in a JWT according to that ID
=> [MOB-4535] login flow refactor

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java
Switching from beta flag to SDKOfflineMode flag for GA
* [MOB-4537](https://iterable.atlassian.net/browse/MOB-4537)
> Changes the flag to check for the non beta flag
=> [MOB-4537] - Change from beta to SDKOfflineMode

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
* [MOB-4260](https://iterable.atlassian.net/browse/MOB-4260)
Avoid bad json situation when disabling device.
If no deviceToken is present, this code change will prevent disableDevice token which returns badJson.
=> [MOB - 4260] - Check device token before disabling

sample-apps/inbox-customization/app/build.gradle, sample-apps/inbox-customization/app/src/main/AndroidManifest.xml, sample-apps/inbox-customization/app/src/main/java/com/iterable/inbox_customization/util/SingleFragmentActivity.kt, sample-apps/inbox-customization/build.gradle
* [MOB-4536](https://iterable.atlassian.net/browse/MOB-4536)
1. Pointing to SDK Version 33
2. Gradle upgraded to version where it understands <queries> tag in manifest
3. Updated variables with null check (?) to remove build errors.
=> [MOB-4536] - Update Sample App

iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableUtil.java
* [MOB-4628](https://iterable.atlassian.net/browse/MOB-4628)
> Removes collection of advertisementId and corresponding constants from the project.
=> [MOB-4628] - Remove ad id collection

CHANGELOG.md, iterableapi-ui/build.gradle, iterableapi/build.gradle, sample-apps/inbox-customization/app/build.gradle
* [MOB-4655](https://iterable.atlassian.net/browse/MOB-4655)
Prepare for 3.4.8
=> Prepare for Release 3.4.8

README.md
Added information about supported Android versions to the README
=> Supported Android versions

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableAuthManager.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java
* [MOB-4439](https://iterable.atlassian.net/browse/MOB-4439)
* adds `authToken` as a field that can be set when setting updating a user's email
=> [MOB-4439] add update email with auth token

CHANGELOG.md, iterableapi-ui/build.gradle, iterableapi/build.gradle, sample-apps/inbox-customization/app/build.gradle
* [MOB-4688](https://iterable.atlassian.net/browse/MOB-4688)
This release will have following changes:
- Added new methods for `setEmail`, `setUserId` and `updateEmail` which accepts `authToken`, providing more ways to pass `authToken` to SDK
- Added two interface methods - `onTokenRegistrationSuccessful` and `onTokenRegistrationFailed`. Override these methods to see if authToken was successfully received by the SDK.  
- `setAuthToken` method is now public allowing additional way to provide `authToken` to SDK.
=> Prepare for 3.4.9

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
* [MOB-4755](https://iterable.atlassian.net/browse/MOB-4755)
* re-categorize functions in `IterableApi.java` as a first step
=> [MOB-4755] reorganize IterableApi.java

iterableapi/src/main/java/com/iterable/iterableapi/IterableActivityMonitor.java
* [MOB-4267](https://iterable.atlassian.net/browse/MOB-4267)
> Adds additional fireTV device checks to trigger callbacks when onActivityResumed is called.
=> adding fireTv check in code to resync onActivityResumed

CHANGELOG.md, iterableapi-ui/build.gradle, iterableapi/build.gradle, sample-apps/inbox-customization/app/build.gradle
* [MOB-4206](https://iterable.atlassian.net/browse/MOB-4206)
* update version to 3.4.10
=> [MOB-4206] version 3.4.10

iterableapi/src/main/java/com/iterable/iterableapi/IterableWebView.java
* [MOB-4986](https://iterable.atlassian.net/browse/MOB-4986)
> Adjusting webview settings to accommodate WYSIWYG html
[MOB-4986]: https://iterable.atlassian.net/browse/MOB-4986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-4986] - webview changes to accomodate WYSIWYG

iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationHelper.java
* [MOB-5532](https://iterable.atlassian.net/browse/MOB-5532)
This pull request does some refactoring and clean up for the custom sound notification channels. Also removing some checks which seem removable.
[MOB-5532]: https://iterable.atlassian.net/browse/MOB-5532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-5532] - Adding remote notification sound

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableConfig.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationHelper.java
* [MOB-5317](https://iterable.atlassian.net/browse/MOB-5317)
This pull request includes the implementation of notification channels based on locally hosted custom sound files.
[MOB-5317]: https://iterable.atlassian.net/browse/MOB-5317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-5317] Notification channels based on locally hosted custom sound

iterableapi/build.gradle, iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedMessage.kt
* [MOB-5393](https://iterable.atlassian.net/browse/MOB-5393)
This pull request sets up the embedded message data types.
[MOB-5393]: https://iterable.atlassian.net/browse/MOB-5393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-5393] creates embedded message data types

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
* [MOB-5695](https://iterable.atlassian.net/browse/MOB-5695)
checkSDKInitialization logs error message. Log warning message instead
[MOB-5695]: https://iterable.atlassian.net/browse/MOB-5695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB - 5695] Log warn instead of error

iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java
* [MOB-5694](https://iterable.atlassian.net/browse/MOB-5694)
> Adding try catch around show and hide webview animation
[MOB-5694]: https://iterable.atlassian.net/browse/MOB-5694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB - 5694] - Add try catch around animation

iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedManager.kt
* [MOB-5785](https://iterable.atlassian.net/browse/MOB-5785)
1. update the local list of messages with remote messages instead of directly assigning remote message to local list.
2. Keep placeholder places for places to call delivery and deletion where new message is identified and old message is identified gotten deleted
[MOB-5785]: https://iterable.atlassian.net/browse/MOB-5785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-5785] - [Manager 2] - Sync remote embedded messages

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
* [MOB-5873](https://iterable.atlassian.net/browse/MOB-5873)
_email, _userID and _authToken to accessible by developers. :)
[MOB-5873]: https://iterable.atlassian.net/browse/MOB-5873?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB - 5873] - Public getters for Email UserID and Auth

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
* [MOB-5893](https://iterable.atlassian.net/browse/MOB-5893)
[MOB-5893]: https://iterable.atlassian.net/browse/MOB-5893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-5893] - Encryption Rebase Fix

iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedManager.kt
* [MOB-5929](https://iterable.atlassian.net/browse/MOB-5929)
This pull request creates a live data that is updated by the local messages queue in the embedded manager. This live data is observed by the embedded UI and updates automatically on each update. The embedded manager serves as the UI fragments view model. Live data is the suggested way of observing changing data in Android.
[MOB-5929]: https://iterable.atlassian.net/browse/MOB-5929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-5929] embedded message live data

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedManager.kt, iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedMessage.kt
* [MOB-5983](https://iterable.atlassian.net/browse/MOB-5983)
> Refactor manager code
[MOB-5983]: https://iterable.atlassian.net/browse/MOB-5983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-5983] - Refactor code

CHANGELOG.md, iterableapi-ui/build.gradle, iterableapi/build.gradle, sample-apps/inbox-customization/app/build.gradle
* [MOB-6053](https://iterable.atlassian.net/browse/MOB-6053)
> Preparing for 3.5.0-alpha1
[MOB-6053]: https://iterable.atlassian.net/browse/MOB-6053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-6053] - Prepare for 3.5.0-alpha1

iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java
* [MOB-5974](https://iterable.atlassian.net/browse/MOB-5974)
- renames the API used for message retrieval
- to be merged in when backend is ready
[MOB-5974]: https://iterable.atlassian.net/browse/MOB-5974?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-5974] route rename

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedManager.kt, iterableapi/src/main/java/com/iterable/iterableapi/IterableRequestTask.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java
* [MOB-5398](https://iterable.atlassian.net/browse/MOB-5398)
This pull request implements embedded message delivery tracking using the custom track event. After the endpoint is ready, this will be connected to the embedded delivery endpoint.
[MOB-5398]: https://iterable.atlassian.net/browse/MOB-5398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-5398] embedded delivery event tracking using custom track event

iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedMessage.kt, iterableapi/src/test/java/com/iterable/iterableapi/IterableEmbeddedMessageTest.kt, iterableapi/src/test/resources/embedded_payload_no_custom_payload.json, iterableapi/src/test/resources/embedded_payload_optional_elements_and_custom_payload.json
* [MOB-5397](https://iterable.atlassian.net/browse/MOB-5397)
* [MOB-6145](https://iterable.atlassian.net/browse/MOB-6145)
This pull request adds the serialization of the button action to the embedded message class.
[MOB-6145]: https://iterable.atlassian.net/browse/MOB-6145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOB-5397]: https://iterable.atlassian.net/browse/MOB-5397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-5397] adds serialization of button action

iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedManager.kt, iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedMessage.kt
Reverting the change
Just reverting the change
=> changes message id back to work with current backend

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java
* [MOB-6055](https://iterable.atlassian.net/browse/MOB-6055)
> Add callbacks to setting email/user id
[MOB-6055]: https://iterable.atlassian.net/browse/MOB-6055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-6055] - [OMNI CG] - Add callbacks to setting email/user id

CHANGELOG.md, iterableapi-ui/build.gradle, iterableapi/build.gradle, iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, sample-apps/inbox-customization/app/build.gradle
* [MOB-6223](https://iterable.atlassian.net/browse/MOB-6223)
> Prepare for release 3.4.12
[MOB-6223]: https://iterable.atlassian.net/browse/MOB-6223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-6223] - Prepare for 3.4.12

iterableapi/build.gradle, iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedMessage.kt, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java
* [MOB-6172](https://iterable.atlassian.net/browse/MOB-6172)
This pull request connects the track embedded message click function to the associated endpoint along with associated unit tests.
[MOB-6172]: https://iterable.atlassian.net/browse/MOB-6172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-6172] connect click event to endpoint

iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedManager.kt, iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedMessage.kt, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableEmbeddedMessageTest.kt, iterableapi/src/test/resources/embedded_payload_no_buttons_no_text.json, iterableapi/src/test/resources/embedded_payload_no_custom_payload.json, iterableapi/src/test/resources/embedded_payload_no_elements_no_custom_payload.json, iterableapi/src/test/resources/embedded_payload_optional_elements_and_custom_payload.json
* [MOB-6185](https://iterable.atlassian.net/browse/MOB-6185)
This pull request updates the message id to match the existing in-app channel.
[MOB-6185]: https://iterable.atlassian.net/browse/MOB-6185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-6185] change message id in payload

iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java
* [MOB-6355](https://iterable.atlassian.net/browse/MOB-6355)
This pull request updates the embedded payloads to include email and userid fields.
[MOB-6355]: https://iterable.atlassian.net/browse/MOB-6355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-6355] updates embedded payloads to include email or userid fields

iterableapi/src/main/java/com/iterable/iterableapi/EmbeddedSessionManager.kt, iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedSession.kt
* [MOB-6232](https://iterable.atlassian.net/browse/MOB-6232)
Creates embedded session manager along with start session function and end session function. Passes dummy session data to analytics call on session end.
[MOB-6232]: https://iterable.atlassian.net/browse/MOB-6232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-6232] creates embedded session manager

iterableapi/src/main/java/com/iterable/iterableapi/EmbeddedImpressionData.kt, iterableapi/src/main/java/com/iterable/iterableapi/EmbeddedSessionManager.kt, iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedImpressionData.kt
* [MOB-6217](https://iterable.atlassian.net/browse/MOB-6217)
- sets up impression tracking functions and connects them to start and end session functions
[MOB-6217]: https://iterable.atlassian.net/browse/MOB-6217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-6217] implement impression tracking functions

iterableapi/src/main/java/com/iterable/iterableapi/EmbeddedImpressionData.kt, iterableapi/src/main/java/com/iterable/iterableapi/EmbeddedSessionManager.kt
* [MOB-6363](https://iterable.atlassian.net/browse/MOB-6363)
[MOB-6363]: https://iterable.atlassian.net/browse/MOB-6363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB - 6363] - Merge embedded session manager to Manager

iterableapi/src/androidTest/java/com/iterable/iterableapi/IterableTestUtils.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedManager.kt
[MOB-6362](https://iterable.atlassian.net/browse/MOB-6362)
> Adds interface method and updates subscription inactive event to all the listeners
[MOB-6362]: https://iterable.atlassian.net/browse/MOB-6362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB - 6362] Update subscription status

iterableapi/src/androidTest/java/com/iterable/iterableapi/IterableTestUtils.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedManager.kt, iterableapi/src/main/java/com/iterable/iterableapi/OfflineRequestProcessor.java, iterableapi/src/main/java/com/iterable/iterableapi/OnlineRequestProcessor.java, iterableapi/src/main/java/com/iterable/iterableapi/RequestProcessor.java
* [MOB-6115](https://iterable.atlassian.net/browse/MOB-6115)
> Feature flagging Embedded messaging
[MOB-6115]: https://iterable.atlassian.net/browse/MOB-6115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB - 6115] EM feature flagging

iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationHelper.java
* [MOB-5132](https://iterable.atlassian.net/browse/MOB-5132)
> Fix deep link issue after app is opened from notification
[MOB-5132]: https://iterable.atlassian.net/browse/MOB-5132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-5132: Fix deep link issue after app is opened from notification

iterableapi-ui/src/main/java/com/iterable/iterableapi/ui/inbox/IterableInboxFragment.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppManager.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableInboxTest.java
* [MOB-6493](https://iterable.atlassian.net/browse/MOB-6493)
> InApp read and remove bug fix
[MOB-6493]: https://iterable.atlassian.net/browse/MOB-6493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB - 6493] - Message read and remove bug fix

CHANGELOG.md, iterableapi-ui/build.gradle, iterableapi/build.gradle, sample-apps/inbox-customization/app/build.gradle
* [MOB-6507](https://iterable.atlassian.net/browse/MOB-6507)
> Prepare for 3.4.14
[MOB-6507]: https://iterable.atlassian.net/browse/MOB-6507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB - 6507] - Prepare for 3.4.14

iterableapi/build.gradle
Removes extra dependency that may be causing tests to fail.
=> removes extra dependency

iterableapi/src/main/AndroidManifest.xml
#553 
- Ensure IterableTrampolineActivity always launched to handle all notifications
- Reverts back to launchMode="singleInstance" to ensure that the activity is always launched
- Use excludeFromRecents="true" to ensure that the activity is not shown in the recent apps list
=> Ensure IterableTrampolineActivity always launched (#553)

CHANGELOG.md, iterableapi-ui/build.gradle, iterableapi/build.gradle, sample-apps/inbox-customization/app/build.gradle
* [MOB-6599](https://iterable.atlassian.net/browse/MOB-6599)
This pull request prepares the version 3.4.15 release.
[MOB-6599]: https://iterable.atlassian.net/browse/MOB-6599?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-6599] prepare for 3.4.15 release

app/src/main/java/com/iterable/androidsdk/NotificationView.java, app/src/main/java/com/iterable/androidsdk/NotificationViewActivity.java, app/src/main/res/layout/activity_notification_view.xml, app/src/main/res/layout/notification_view.xml, iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationHelper.java
=> Notification view implementation

.github/workflows/jira.yml, README.md, app/build.gradle, iterableapi-ui/src/main/java/com/iterable/iterableapi/ui/inbox/IterableInboxFragment.java, iterableapi/build.gradle, iterableapi/src/main/AndroidManifest.xml, iterableapi/src/main/java/com/iterable/iterableapi/IterableActivityMonitor.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableAuthManager.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableConfig.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableDataRegion.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppManager.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationBuilder.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationHelper.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableRequestTask.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableUtil.java, iterableapi/src/main/java/com/iterable/iterableapi/util/DeviceInfoUtils.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableConfigTest.kt, iterableapi/src/test/java/com/iterable/iterableapi/IterableInboxTest.java
> This pull request merges master into embedded.
=> Merge master into embedded

CHANGELOG.md, iterableapi-ui/build.gradle, iterableapi/build.gradle, sample-apps/inbox-customization/app/build.gradle
* [MOB-7048](https://iterable.atlassian.net/browse/MOB-7048)
> Prepare for 3.4.16
[MOB-7048]: https://iterable.atlassian.net/browse/MOB-7048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-7048] - Prepare for 3.4.16

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
* [MOB-7044](https://iterable.atlassian.net/browse/MOB-7044)
> This pull request adds the reset of the embedded manager on the logout of the SDK.
[MOB-7044]: https://iterable.atlassian.net/browse/MOB-7044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-7044] reset embedded manager on logout

gradle/wrapper/gradle-wrapper.properties, iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedManager.kt, iterableapi/src/test/java/com/iterable/iterableapi/IterableEmbeddedManagerTest.java, iterableapi/src/test/resources/embedded_payload_multiple_1.json, iterableapi/src/test/resources/embedded_payload_multiple_2.json, iterableapi/src/test/resources/embedded_payload_single_1.json, iterableapi/src/test/resources/embedded_payload_single_2.json
* [MOB-6733](https://iterable.atlassian.net/browse/MOB-6733)
> This pull request restructures local storage and updating message for placements. This also allows for messages to be pulled for a placement id.
[MOB-6733]: https://iterable.atlassian.net/browse/MOB-6733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-6733] update local storage and handlers

CHANGELOG.md, iterableapi-ui/build.gradle, iterableapi/build.gradle, sample-apps/inbox-customization/app/build.gradle
* [MOB-7312](https://iterable.atlassian.net/browse/MOB-7312)
> This pull request prepares for the 3.5.0-beta1 release.
[MOB-7312]: https://iterable.atlassian.net/browse/MOB-7312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-7312] prepare for 3.5.0-beta1 release

iterableapi/src/test/java/com/iterable/iterableapi/IterableEmbeddedPlacementTest.kt, iterableapi/src/test/resources/embedded_payload_multiple_1.json, iterableapi/src/test/resources/embedded_payload_multiple_2.json, iterableapi/src/test/resources/embedded_payload_multiple_3.json, iterableapi/src/test/resources/embedded_payload_single_1.json, iterableapi/src/test/resources/embedded_payload_single_2.json
* [MOB-7349](https://iterable.atlassian.net/browse/MOB-7349)
> This pull request adds unit tests for serialization and deserialization of a payload with multiple placements.
[MOB-7349]: https://iterable.atlassian.net/browse/MOB-7349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-7349] placements serialization tests

iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedManager.kt
* [MOB-7315](https://iterable.atlassian.net/browse/MOB-7315)
> This pull request sets up custom action handling in the handleEmbeddedClick method.
[MOB-7315]: https://iterable.atlassian.net/browse/MOB-7315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-7315] sets up custom action handling

iterableapi-ui/src/main/java/com/iterable/iterableapi/ui/embedded/IterableEmbeddedView.kt, iterableapi-ui/src/main/java/com/iterable/iterableapi/ui/embedded/IterableEmbeddedViewConfig.kt
* [MOB-6876](https://iterable.atlassian.net/browse/MOB-6876)
> This pull request updates the button naming to primary and secondary.
[MOB-6876]: https://iterable.atlassian.net/browse/MOB-6876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-6876] update button naming

iterableapi/src/main/java/com/iterable/iterableapi/IterableFirebaseMessagingService.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableFirebaseMessagingServiceTest.java, iterableapi/src/test/resources/push_payload_embedded_update.json
* [MOB-7556](https://iterable.atlassian.net/browse/MOB-7556)
> In this update, we have modified the notification code to accommodate the 'UpdateEmbedded' notification type. Furthermore, we've included unit test cases to validate these changes.
[MOB-7556]: https://iterable.atlassian.net/browse/MOB-7556
=> [MOB-7556] support mid session eligibility

iterableapi-ui/src/main/java/com/iterable/iterableapi/ui/embedded/IterableEmbeddedView.kt, iterableapi-ui/src/main/res/layout-v21/banner_view.xml, iterableapi-ui/src/main/res/layout-v21/card_view.xml, iterableapi-ui/src/main/res/layout/banner_view.xml, iterableapi-ui/src/main/res/layout/card_view.xml, iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedPlacement.kt, iterableapi/src/test/java/com/iterable/iterableapi/IterableEmbeddedPlacementTest.kt
* [MOB-7460](https://iterable.atlassian.net/browse/MOB-7460)
> This pull request adds content description to the image view from the embedded message payload. Also, updates the `IterableEmbeddedMessage` class and serialization with added `mediaUrlCaption`.
[MOB-7460]: https://iterable.atlassian.net/browse/MOB-7460?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-7460] adds content description to image view from payload

iterableapi-ui/src/main/res/layout-v21/banner_view.xml, iterableapi-ui/src/main/res/layout-v21/card_view.xml, iterableapi-ui/src/main/res/layout-v21/notification_view.xml, iterableapi-ui/src/main/res/layout/banner_view.xml, iterableapi-ui/src/main/res/layout/card_view.xml, iterableapi-ui/src/main/res/layout/notification_view.xml, iterableapi/src/test/java/com/iterable/iterableapi/IterableEmbeddedPlacementTest.kt
* [MOB-7625](https://iterable.atlassian.net/browse/MOB-7625)
> This pull request updates the layouts for the OOTB views to limit the number of lines for the title and body. I also made updates to some of the layout and to the width of the body text to align more with the design.
[MOB-7625]: https://iterable.atlassian.net/browse/MOB-7625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-7625] OOTB layout clean up

iterableapi/src/main/java/com/iterable/iterableapi/IterableConfig.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedManager.kt
* [MOB-7734](https://iterable.atlassian.net/browse/MOB-7734)
Disables fetching embedded messages by default and adds a config to turn it on.
[MOB-7734]: https://iterable.atlassian.net/browse/MOB-7734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-7734] embedded config

iterableapi-ui/src/main/res/layout-v21/card_view.xml, iterableapi-ui/src/main/res/layout/card_view.xml, iterableapi-ui/src/main/res/values/dimens.xml
* [MOB-7749](https://iterable.atlassian.net/browse/MOB-7749)
> This pull request adds dimension value to card text container to resolve UI issue. Text container was not given a proper height to fit two lines of text for title and body.
[MOB-7749]: https://iterable.atlassian.net/browse/MOB-7749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-7749] card text container fix

iterableapi-ui/src/main/res/layout-v21/card_view.xml, iterableapi-ui/src/main/res/layout-v21/notification_view.xml, iterableapi-ui/src/main/res/layout/card_view.xml, iterableapi-ui/src/main/res/layout/notification_view.xml
> This pull request updates text widths to match parent with an end margin.
=> sets width of text to match parent

iterableapi-ui/build.gradle, iterableapi/build.gradle, sample-apps/inbox-customization/app/build.gradle
* [MOB-7783](https://iterable.atlassian.net/browse/MOB-7783)
> Prepare for 3.5.0
[MOB-7783]: https://iterable.atlassian.net/browse/MOB-7783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-7783] - Prepare for 3.5.0

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
* [MOB-7795](https://iterable.atlassian.net/browse/MOB-7795)
> We have removed JWT token generation while user not logged in.
[MOB-7795]: https://iterable.atlassian.net/browse/MOB-7795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove JWT token generation while user not logged in

iterableapi/src/main/java/com/iterable/iterableapi/IterableAuthManager.java
* [MOB-7856](https://iterable.atlassian.net/browse/MOB-7856)
> Prevents jwt refesh being called if user is logged out within the scheduled time
[MOB-7856]: https://iterable.atlassian.net/browse/MOB-7856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-7856] - Add user logged in check

README.md
README updates for Embedded Messaging
=> [DOCS-4514] README updates for Embedded Messaging

iterableapi/src/main/java/com/iterable/iterableapi/IterablePushNotificationUtil.java
* [MOB-8111](https://iterable.atlassian.net/browse/MOB-8111)
> Pass intent to launching Activity
[MOB-8111]: https://iterable.atlassian.net/browse/MOB-8111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-8111] - Pass intent to launching Activity

iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedManager.kt
* [MOB-8207](https://iterable.atlassian.net/browse/MOB-8207)
> Disable Embedded Manager Activity listeners when EM feature itself is disabled
[MOB-8207]: https://iterable.atlassian.net/browse/MOB-8207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-8207] - EM bug fix

.github/workflows/build.yml, .github/workflows/jira.yml
* [MOB-8396](https://iterable.atlassian.net/browse/MOB-8396)
Address [ISRR-515](https://iterable.atlassian.net/browse/ISRR-515)
Libraries:
https://github.com/actions/checkout/tree/b4ffde65f46336ab88eb53be808477a3936bae11/
https://github.com/gradle/wrapper-validation-action/tree/216d1ad2b3710bf005dc39237337b9673fd8fcd5/
https://github.com/actions/setup-java/tree/d202f5dbf7256730fb690ec59f6381650114feb2/
https://github.com/actions/upload-artifact/tree/65462800fd760344b1a7b4382951275a0abb4808/
https://github.com/reactivecircus/android-emulator-runner/tree/6b0df4b0efb23bb0ec63d881db79aefbc976e4b2/
https://github.com/actions/download-artifact/tree/65a9edc5881444af0b9093a5e628f2fe47ea3b2e/
[MOB-8396]: https://iterable.atlassian.net/browse/MOB-8396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …
=> [MOB-8396] address git action commit hash vulnerability and update to latest

CHANGELOG.md, iterableapi-ui/build.gradle, iterableapi/build.gradle, sample-apps/inbox-customization/app/build.gradle
* [MOB-8536](https://iterable.atlassian.net/browse/MOB-8536)
[MOB-8536]: https://iterable.atlassian.net/browse/MOB-8536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-8536] - Prepare for 3.5.2

iterableapi/src/main/java/com/iterable/iterableapi/AnonymousUserManager.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java
* [MOB-8621](https://iterable.atlassian.net/browse/MOB-8621)
> This pull request updates the track purchase signatures to add attribution info.
[MOB-8621]: https://iterable.atlassian.net/browse/MOB-8621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-8621] updates track purchase signatures

iterableapi/src/main/java/com/iterable/iterableapi/IterableAuthManager.java
* [MOB-8974](https://iterable.atlassian.net/browse/MOB-8974)
> Marks token as invalid when token's expiration dequeuing fails.
[MOB-8974]: https://iterable.atlassian.net/browse/MOB-8974?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB - 8974] - Adding Bug fixes

iterableapi/src/androidTest/java/com/iterable/iterableapi/util/ComplexCriteriaCheckerTest.java, iterableapi/src/androidTest/java/com/iterable/iterableapi/util/CriteriaCompletionCheckerTest.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java, iterableapi/src/main/java/com/iterable/iterableapi/util/CriteriaCompletionChecker.java
=> Support minMatch and added complex critria unit tests

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
=> formatting

iterableapi/src/androidTest/java/com/iterable/iterableapi/util/ComplexCriteriaCheckerTest.java, iterableapi/src/androidTest/java/com/iterable/iterableapi/util/CriteriaCompletionCheckerTest.java, iterableapi/src/androidTest/java/com/iterable/iterableapi/util/CriteriaCompletionComparatorTest.java, iterableapi/src/main/java/com/iterable/iterableapi/AnonymousUserManager.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java, iterableapi/src/main/java/com/iterable/iterableapi/util/CriteriaCompletionChecker.java
*[MOB-8943](https://iterable.atlassian.net/browse/MOB-8943)
Support for IsSet criteria
Added unit tests
[MOB-8943]: https://iterable.atlassian.net/browse/MOB-8943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Itbl track anon user purchase update fix

CHANGELOG.md, iterableapi-ui/build.gradle, iterableapi/build.gradle, sample-apps/inbox-customization/app/build.gradle
* [MOB-8921](https://iterable.atlassian.net/browse/MOB-8921)
> Prepare for 3.5.3
[MOB-8921]: https://iterable.atlassian.net/browse/MOB-8921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-8921] - Prepare for 3.5.3

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
=> removes redundant call

iterableapi/src/androidTest/java/com/iterable/iterableapi/util/DoesNotEqualCriteriaMatchTest.java, iterableapi/src/main/java/com/iterable/iterableapi/util/MatchComparator.java
* [MOB-9138](https://iterable.atlassian.net/browse/MOB-9138)
> Resolves DoesNotEqual criteria match issue.
> Video attached to the ticket, See a JIRA ticket for the video.
[MOB-9138]: https://iterable.atlassian.net/browse/MOB-9138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-9138: Resolves DoesNotEqual criteria match issue

iterableapi/src/main/java/com/iterable/iterableapi/AnonymousUserManager.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableConfig.java
* [MOB-8825](https://iterable.atlassian.net/browse/MOB-8825)
>  limit the number of stored events and make the number of synced events configurable.
> Video attached to the ticket, See a JIRA ticket for the video
[MOB-8825]: https://iterable.atlassian.net/browse/MOB-8825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB 8825 - limit the number of stored events and make the number of synced events configurable

iterableapi/src/main/java/com/iterable/iterableapi/IterableConfig.java
* [MOB-9317](https://iterable.atlassian.net/browse/MOB-9317)
> This pull request sets the event threshold to 50.
[MOB-9317]: https://iterable.atlassian.net/browse/MOB-9317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-9317] sets event threshold to 50

iterableapi/src/androidTest/java/com/iterable/iterableapi/util/DataTypeComparatorSearchQueryCriteriaTest.java
* [MOB-9315](https://iterable.atlassian.net/browse/MOB-9315)
> Write automated unit tests for different field types and comparator types
> Video attached to the ticket, See a JIRA ticket for the video.
[MOB-9314]: https://iterable.atlassian.net/browse/MOB-9314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOB-9315]: https://iterable.atlassian.net/browse/MOB-9315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-9315] Written automated unit test cases for different field types and comparator types

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
* [MOB-9348](https://iterable.atlassian.net/browse/MOB-9348)
> This pull request adds a check for merging and replaying of events to occur only when anonymous user tracking is enabled.
[MOB-9348]: https://iterable.atlassian.net/browse/MOB-9348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-9348] disable merge and replay when AUT is disabled

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
* [MOB-9430](https://iterable.atlassian.net/browse/MOB-9430)
> This pull request set isEmail correctly for setUserId and setEmail.
[MOB-9430]: https://iterable.atlassian.net/browse/MOB-9430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-9430] update attemptAndProcessMerge

iterableapi/src/main/java/com/iterable/iterableapi/AnonymousUserMerge.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiMergeUserEmailTests.java
* [MOB-9422](https://iterable.atlassian.net/browse/MOB-9422)
> This pull request makes the tryMergeUser function private and removes source email from parameters.
[MOB-9422]: https://iterable.atlassian.net/browse/MOB-9422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-9422] makes tryMergeUser private

iterableapi/src/androidTest/java/com/iterable/iterableapi/util/DataTypeComparatorArrayInputCriteriaTest.java, iterableapi/src/main/java/com/iterable/iterableapi/util/CriteriaCompletionChecker.java
* [MOB-9312](https://iterable.atlassian.net/browse/MOB-9312)
> Fully supports comparison for data in Array data with all comparator types
[MOB-9312]: https://iterable.atlassian.net/browse/MOB-9312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> - MOB-9312: Fully support comparison for Array data types

iterableapi/src/androidTest/java/com/iterable/iterableapi/util/NestedCriteriaMatchTest.java, iterableapi/src/main/java/com/iterable/iterableapi/util/CriteriaCompletionChecker.java
* [MOB-9179](https://iterable.atlassian.net/browse/MOB-9179)
> Support nested field types
>Video attached to the ticket, See a JIRA ticket for the video
[MOB-9179]: https://iterable.atlassian.net/browse/MOB-9179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-9179: Support nested field types

iterableapi/src/androidTest/java/com/iterable/iterableapi/util/IsOneOfAndIsNotOneOfCriteriaMatchTest.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java, iterableapi/src/main/java/com/iterable/iterableapi/util/CriteriaCompletionChecker.java
* [MOB-9386](https://iterable.atlassian.net/browse/MOB-9386)
> Support isOneOf and isNotOneOf comparator
>Video attached to the ticket, See a JIRA ticket for the video
[MOB-9386]: https://iterable.atlassian.net/browse/MOB-9386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-9386 Support isOneOf and isNotOneOf comparator

iterableapi/src/main/java/com/iterable/iterableapi/AnonymousUserManager.java, iterableapi/src/main/java/com/iterable/iterableapi/OnlineRequestProcessor.java
* [MOB-9238](https://iterable.atlassian.net/browse/MOB-9238)
> Replayed events don't have proper createdAt timestamp
> Video attached to the ticket, See a JIRA ticket for the video
[MOB-9238]: https://iterable.atlassian.net/browse/MOB-9238?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-9238 Replayed events don't have proper createdAt timestamp

iterableapi/src/main/java/com/iterable/iterableapi/AnonymousUserManager.java
* [MOB-9001](https://iterable.atlassian.net/browse/MOB-9001)
> This pull request refactors anonymous user manager for maintainability. Also updates updateUser to call IterableApiClient class directly.
[MOB-9001]: https://iterable.atlassian.net/browse/MOB-9001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-9001] refactoring anonymous user manager

iterableapi/src/main/java/com/iterable/iterableapi/util/CriteriaCompletionChecker.java
* [MOB-9570](https://iterable.atlassian.net/browse/MOB-9570)
> This pull request refactors the comparison functions.
[MOB-9570]: https://iterable.atlassian.net/browse/MOB-9570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-9570] refactoring comparison functions

iterableapi/src/androidTest/java/com/iterable/iterableapi/util/CombinationLogicEventTypeCriteriaTest.java, iterableapi/src/androidTest/java/com/iterable/iterableapi/util/ComplexCriteriaCheckerTest.java, iterableapi/src/androidTest/java/com/iterable/iterableapi/util/CriteriaCompletionCheckerTest.java, iterableapi/src/androidTest/java/com/iterable/iterableapi/util/CriteriaCompletionComparatorTest.java, iterableapi/src/androidTest/java/com/iterable/iterableapi/util/DataTypeComparatorArrayInputCriteriaTest.java, iterableapi/src/androidTest/java/com/iterable/iterableapi/util/DataTypeComparatorSearchQueryCriteriaTest.java, iterableapi/src/androidTest/java/com/iterable/iterableapi/util/DoesNotEqualCriteriaMatchTest.java, iterableapi/src/androidTest/java/com/iterable/iterableapi/util/IsOneOfAndIsNotOneOfCriteriaMatchTest.java, iterableapi/src/androidTest/java/com/iterable/iterableapi/util/NestedCriteriaMatchTest.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java, iterableapi/src/main/java/com/iterable/iterableapi/util/CriteriaCompletionChecker.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiMergeUserEmailTests.java
* [MOB-9583](https://iterable.atlassian.net/browse/MOB-9583)
> This pull request updates "criterias" to "criteriaSets".
[MOB-9583]: https://iterable.atlassian.net/browse/MOB-9583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-9583] update "criterias" to "criteriaSets"

iterableapi/src/test/java/com/iterable/iterableapi/IterableApiCustomEventTests.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableUtilRule.java
* [MOB-9203](https://iterable.atlassian.net/browse/MOB-9203)
> Add test to validate object created by custom event api calls
[MOB-9203]: https://iterable.atlassian.net/browse/MOB-9203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-9203 - Add test to validate object created by custom event api calls

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
* [MOB-9519](https://iterable.atlassian.net/browse/MOB-9519)
> This pull request logs out the previous user and sets the user id or email before attempting to merge and replaying events so that the user is set in the json payload before making the request.
[MOB-9519]: https://iterable.atlassian.net/browse/MOB-9519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-9519] fix event replay

iterableapi/src/test/java/com/iterable/iterableapi/IterableApiCustomEventTests.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiMergeUserEmailTests.java
* [MOB-9620](https://iterable.atlassian.net/browse/MOB-9620)
> This pull request adds unit tests to cover all the combinations of the identity resolution parameter.
[MOB-9620]: https://iterable.atlassian.net/browse/MOB-9620?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-9620] unit test updates for identity resolution combinations

iterableapi/src/androidTest/java/com/iterable/iterableapi/util/MultiLevelNestedCriteriaMatchTest.java, iterableapi/src/main/java/com/iterable/iterableapi/util/CriteriaCompletionChecker.java
* [MOB-9651](https://iterable.atlassian.net/browse/MOB-9651)
* [MOB-9536](https://iterable.atlassian.net/browse/MOB-9536)
> Add support to check for nested criteria a.b.c
[MOB-9651]: https://iterable.atlassian.net/browse/MOB-9651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOB-9536]: https://iterable.atlassian.net/browse/MOB-9536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-9651 - Add support to check for nested criteria a.b.c

iterableapi/src/androidTest/java/com/iterable/iterableapi/util/CombinationComplexCriteriaCheckerTest.java
* [MOB-9311](https://iterable.atlassian.net/browse/MOB-9311)
> Write automated unit tests against Complex criteria
[MOB-9311]: https://iterable.atlassian.net/browse/MOB-9311?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Write automated unit tests against Complex criteria

app/.idea/workspace.xml, app/src/main/java/com/iterable/androidsdk/AnonTrackingTestActivity.java, app/src/main/res/layout/activity_test.xml, iterableapi/src/main/java/com/iterable/iterableapi/AnonymousUserManager.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiMergeUserEmailTests.java
* [MOB-9679](https://iterable.atlassian.net/browse/MOB-9679)
> Keep AUT off until consent to track has been granted
> Video attached to the ticket, See a JIRA ticket for the video
[MOB-9679]: https://iterable.atlassian.net/browse/MOB-9679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB 9679 - Keep AUT off until consent to track has been granted

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
* [MOB-9931](https://iterable.atlassian.net/browse/MOB-9931)
> This pull request adds a check for AUT enablement when consent is given. This aligns with iOS SDK.
[MOB-9931]: https://iterable.atlassian.net/browse/MOB-9931?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-9931] adds AUT enablement check

iterableapi/src/main/java/com/iterable/iterableapi/AnonymousUserManager.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java
* [MOB-9997](https://iterable.atlassian.net/browse/MOB-9997)
* [MOB-9998](https://iterable.atlassian.net/browse/MOB-9998)
[MOB-9997]: https://iterable.atlassian.net/browse/MOB-9997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOB-9998]: https://iterable.atlassian.net/browse/MOB-9998?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-9997] bug fix user update aggregation and update user rearchitect

iterableapi/src/main/java/com/iterable/iterableapi/AnonymousUserManager.java
* [MOB-10031](https://iterable.atlassian.net/browse/MOB-10031)
> This pull request updates the user update aggregation to replace nested arrays instead of appending to them.
[MOB-10031]: https://iterable.atlassian.net/browse/MOB-10031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-10031] user update array fix

iterableapi/src/androidTest/java/com/iterable/iterableapi/util/SinglePrimitiveArrayNestedCriteriaMatchTest.java, iterableapi/src/main/java/com/iterable/iterableapi/util/CriteriaCompletionChecker.java
* [MOB-9716](https://iterable.atlassian.net/browse/MOB-9716)
> Single primitive array bug
[MOB-9716]: https://iterable.atlassian.net/browse/MOB-9716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-9716 - single primitive array bug

iterableapi/src/main/java/com/iterable/iterableapi/AnonymousUserManager.java
* [MOB-10054](https://iterable.atlassian.net/browse/MOB-10054)
> This pull request updates the method name to createAnonymousUser
[MOB-10054]: https://iterable.atlassian.net/browse/MOB-10054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-10054] renames createAnonymousUser

app/src/main/java/com/iterable/androidsdk/AnonTrackingTestActivity.java, iterableapi/src/main/java/com/iterable/iterableapi/AnonymousUserManager.java, iterableapi/src/main/java/com/iterable/iterableapi/GenerateJWTSuccess.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableAuthManager.java, iterableapi/src/main/java/com/iterable/iterableapi/util/IterableJwtGenerator.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiAuthJWTTests.java
* [MOB-9745](https://iterable.atlassian.net/browse/MOB-9745)
> Update mobile SDKs to support fetching a new JWT to use for the destinationUserId / destinationEmail when calling merge
> Video attached to the ticket, See a JIRA ticket for the video
[MOB-9745]: https://iterable.atlassian.net/browse/MOB-9745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-9745] Update mobile SDKs to support fetching a new JWT to use for the destinationUserId / destinationEmail when calling merge

app/src/main/java/com/iterable/androidsdk/AnonTrackingTestActivity.java, iterableapi/src/main/java/com/iterable/iterableapi/AnonymousUserManager.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiAuthJWTTests.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiMergeUserEmailTests.java
* [MOB-10088](https://iterable.atlassian.net/browse/MOB-10088)
> This pull request renames the consent setting function to setVisitorUsageTracked.
[MOB-10088]: https://iterable.atlassian.net/browse/MOB-10088?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-10088] renaming to setVisitorUsageTracked

app/src/main/java/com/iterable/androidsdk/AnonTrackingTestActivity.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableConfig.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiAuthJWTTests.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiCustomEventTests.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiMergeUserEmailTests.java
* [MOB-10092](https://iterable.atlassian.net/browse/MOB-10092)
> This pull request renames the config to enableAnonActivation.
[MOB-10092]: https://iterable.atlassian.net/browse/MOB-10092?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-10092] renames config to enableAnonActivation

iterableapi/src/main/java/com/iterable/iterableapi/AnonymousUserManager.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
* [MOB-10137](https://iterable.atlassian.net/browse/MOB-10137)
> This pull request clears the locally stored data when replay is false.
[MOB-10137]: https://iterable.atlassian.net/browse/MOB-10137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-10137] clears locally stored data when replay is false

iterableapi/src/main/java/com/iterable/iterableapi/AnonymousUserManager.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiMergeUserEmailTests.java
* [MOB-10109](https://iterable.atlassian.net/browse/MOB-10109)
> This pull request updates the merge tests and fixes update user bug.
[MOB-10109]: https://iterable.atlassian.net/browse/MOB-10109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-10098] fixes update user bug

iterableapi/src/test/java/com/iterable/iterableapi/IterableApiMergeUserEmailTests.java
* [MOB-10109](https://iterable.atlassian.net/browse/MOB-10109)
[MOB-10109]: https://iterable.atlassian.net/browse/MOB-10109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-10109] updates merge tests

CHANGELOG.md, iterableapi-ui/build.gradle, iterableapi/build.gradle, sample-apps/inbox-customization/app/build.gradle
* [MOB-10403](https://iterable.atlassian.net/browse/MOB-10403)
> Prepare for 3.5.4
[MOB-10403]: https://iterable.atlassian.net/browse/MOB-10403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-10403] - Prepare for 3.5.4

CHANGELOG.md, iterableapi-ui/build.gradle, iterableapi/build.gradle, sample-apps/inbox-customization/app/build.gradle
* [MOB-10521](https://iterable.atlassian.net/browse/MOB-10521)
> This pull request prepares for the version 3.5.5 release.
[MOB-10521]: https://iterable.atlassian.net/browse/MOB-10521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-10521] prepares for version 3.5.5 release

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> This PR makes keychain private. Accidentally make keychain public during testing.
=> [MOB-XXXX] makes keychain private

CHANGELOG.md, iterableapi-ui/build.gradle, iterableapi/build.gradle, sample-apps/inbox-customization/app/build.gradle, sample-apps/inbox-customization/build.gradle
* [MOB-10597](https://iterable.atlassian.net/browse/MOB-10597)
> This pull requests prepares for the version 3.5.7 release.
[MOB-10597]: https://iterable.atlassian.net/browse/MOB-10597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-10597] prepares for version 3.5.7 release

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
=> [MOB-9446] Logic fix for notifications

CHANGELOG.md, iterableapi-ui/build.gradle, iterableapi/build.gradle, sample-apps/inbox-customization/app/build.gradle, sample-apps/inbox-customization/build.gradle
* [MOB-10637](https://iterable.atlassian.net/browse/MOB-10637)
> This pull request prepares for the version 3.5.9 release.
[MOB-10637]: https://iterable.atlassian.net/browse/MOB-10637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-10637] prepares for version 3.5.9 release

.github/workflows/prepare-release.yml
* [MOB-10743](https://iterable.atlassian.net/browse/MOB-10743)
> YAML for Pre-Release Automation
[MOB-10743]: https://iterable.atlassian.net/browse/MOB-10743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Mob 10743] - pre release automation

iterableapi/src/main/java/com/iterable/iterableapi/AnonymousUserManager.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiMergeUserEmailTests.java
* [MOB-10807](https://iterable.atlassian.net/browse/MOB-10807)
> Multiple unique anonymous users are created.
[MOB-10807]: https://iterable.atlassian.net/browse/MOB-10807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MOB-10807 Fix AUT issue where multiple users are created

.github/workflows/build.yml, app/build.gradle, app/src/main/AndroidManifest.xml, iterableapi-ui/build.gradle, iterableapi/build.gradle, iterableapi/src/main/AndroidManifest.xml, iterableapi/src/test/java/com/iterable/iterableapi/IterableNotificationTest.java, sample-apps/inbox-customization/app/build.gradle
=> Removing workaround files

CHANGELOG.md, iterableapi-ui/build.gradle, iterableapi/build.gradle, sample-apps/inbox-customization/app/build.gradle
* [MOB-11653](https://iterable.atlassian.net/browse/MOB-11653)
> Prepare for 3.5.14
[MOB-11653]: https://iterable.atlassian.net/browse/MOB-11653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-11653] - Prepare for 3.5.14

iterableapi/src/main/java/com/iterable/iterableapi/UnknownUserManager.java
* [MOB-11705](https://iterable.atlassian.net/browse/MOB-11705)
> This pull request removes a redundant function in the unknown user manager and uses the existing utility function. 
[MOB-11705]: https://iterable.atlassian.net/browse/MOB-11705?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-11705] use existing utility function to get current time

CHANGELOG.md, iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java, iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiAuthJWTTests.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiCustomEventTests.java, iterableapi/src/test/java/com/iterable/iterableapi/IterableApiMergeUserEmailTests.java
* [MOB-11686](https://iterable.atlassian.net/browse/MOB-11686)
This pull request completes the renaming by updating the endpoints and associated fields, and changelog.
[MOB-11686]: https://iterable.atlassian.net/browse/MOB-11686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-11686] renaming endpoints

CHANGELOG.md, iterableapi-ui/build.gradle, iterableapi/build.gradle, sample-apps/inbox-customization/app/build.gradle
* [MOB-XXXX](https://iterable.atlassian.net/browse/MOB-11814)
> Prepare for 3.6.0-beta3
=> [MOB-11814] - Prepare for Beta 3.6.0-beta3

CHANGELOG.md, iterableapi-ui/build.gradle, iterableapi/build.gradle, sample-apps/inbox-customization/app/build.gradle
* [MOB-11912](https://iterable.atlassian.net/browse/MOB-11912)
> Prepare for release 3.5.15
[MOB-11912]: https://iterable.atlassian.net/browse/MOB-11912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-11912] - Prepare for release 3.5.15

iterableapi/src/main/java/com/iterable/iterableapi/OfflineRequestProcessor.java
* [MOB-11858](https://iterable.atlassian.net/browse/MOB-11858)
> SDK will now support storing disable device API requests when device looses network. It will persist the request and once network re-establishes, will make request.
[MOB-11858]: https://iterable.atlassian.net/browse/MOB-11858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB - 11858] - Disable push API in offline mode

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
* [MOB-11993](https://iterable.atlassian.net/browse/MOB-11993)
> This pull request adds consent tracking on the failure handler for register device. This allows consent to be called in the scenario where a profile is generated when the device registration fails.
[MOB-11993]: https://iterable.atlassian.net/browse/MOB-11993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MOB-11993] adds consent tracking to register device failure handler
