Iterable/iterable-android-sdk

iterableapi/src/androidTest/java/com/iterable/iterableapi/IterableNotificationTest.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationBuilder.java

For compatibility with support library version 27.

[ITBL-4495] Remove references to internal fields in NotificationCompat.Builder

---

iterableapi/src/androidTest/java/com/iterable/iterableapi/IterableApiDeeplinkTest.java
iterableapi/src/androidTest/java/com/iterable/iterableapi/IterableApiResponseTest.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableDeeplinkManager.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableRequest.java

**Changed:** getAndTrackDeeplink was previously returning the original app link URL (if the response is 302), the URL passed to it (if it's not an Iterable link), or the error message from the response body (if it returned with code >= 400). It only returns a URL now and doesn't return the error text in case of 400 errors, same as on iOS. Is it a desired change?

[ITBL-4563] Extract redirect handing code from IterableRequest

---

iterableapi/src/main/java/com/iterable/iterableapi/IterablePushActionReceiver.java

`setPayloadData` was defined but wasn't being used. This makes sure to set the payload data on GCM messages

Set payload data onReceive

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java

Adds a new method that returns all of payload as a JSONObject. It handles JSON errors the same way other methods do in this file.
Context: https://github.com/Iterable/iterable-android-sdk/pull/50#issuecomment-408253595

Add method to get all payload data

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableConfig.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableRequest.java
iterableapi/src/main/java/com/iterable/iterableapi/ddl/DeviceInfo.java
iterableapi/src/main/java/com/iterable/iterableapi/ddl/MatchFpResponse.java
iterableapi/src/test/java/com/iterable/iterableapi/DeferredDeepLinkTest.java
iterableapi/src/test/resources/fp_match_fail.json
iterableapi/src/test/resources/fp_match_success.json

- Added a new config option: `checkForDeferredDeeplink` to enable DDL
- Send a device fingerprint on first launch
- If matched, call the URL handler with the original link

[ITBL-6259] Deferred deep linking support

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterablePushRegistration.java
iterableapi/src/main/java/com/iterable/iterableapi/IterablePushRegistrationData.java
iterableapi/src/test/java/com/iterable/iterableapi/IterablePushRegistrationTest.java
iterableapi/src/test/java/com/iterable/iterableapi/unit/IterableTestUtils.java

Due to the asynchronous nature of device registration in the Android SDK, disableDevice actually gets handled after the new userId/email is already set. To make sure it is called with the correct email/userId, we should pass that directly.

[MOB-48] Pass email & userId to registerDeviceToken/disableToken calls to avoid concurrency issues

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java

Use 'preferUserId' flag to create a user by userId instead of the deprecated createUserForUserId API.

[MOB-34] Use 'preferUserId' flag to create a user by userId instead of the old API

---

README.md
iterableapi/src/main/AndroidManifest.xml
iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableFirebaseInstanceIDService.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableFirebaseMessagingService.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationBuilder.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableFirebaseMessagingServiceTest.java

Add public methods to be called from a custom FirebaseMessagingService subclass if the app has one.

[MOB-109] Custom Firebase messaging service support

---

iterableapi/src/androidTest/AndroidManifest.xml
iterableapi/src/main/AndroidManifest.xml
iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationBuilder.java

Get application name by using loadLabel so we can support both resource and plain text application labels
Also, remove `label` from the Manifest because that's not something we want to merge into the app manifest.

[MOB-165] Get application name by using loadLabel

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java

[MOB-95] Don't switch to email as identifier after calling updateEmail with userId

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java

Send `clickedUrl` instead of `urlClick` to match the API spec.

[MOB-284] Pass the correct parameter for inAppClick - clickedUrl

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableDeeplinkManager.java

This has been causing a lot of test failures lately.. The emulator is extremely slow on TravisCI.
Also, we’ve previously bumped the other, general timeout for requests to 3 seconds, so we should do the same here.

[MOB-305] Increase timeout in IterableDeeplinkManager to 3 seconds

---

iterableapi/src/androidTest/java/com/iterable/iterableapi/IterableApiDeeplinkTest.java

These tests are flaky, and they run on an emulator. Increase the timeout from 1 second to 5 seconds to unflake them.

[MOB-461] Increase timeout in IterableApiDeeplinkTest

---

.codecov.yml

This is enabled by default, and causes it to show a red X next to the commit/PR, implying failed tests. A comment from codecov in the PR should be enough.

[MOB-462] Disable Codecov commit status

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableActivityMonitor.java

[MOB-489] Fix a NullPointerException that may occur in IterableActivityMonitor if it's initialized after the application is started

---

README.md
iterableapi/build.gradle
iterableapi/src/main/AndroidManifest.xml
iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableFirebaseInstanceIDService.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableFirebaseMessagingService.java

Google has recently removed FirebaseInstanceIdService class from the Firebase Messaging library. We need to remove it in our SDK to ensure compatibility with the newer version of the Firebase library.
Keeping `IterableFirebaseInstanceIDService` with one static method for backwards compatibility.
Fixes #118.

[MOB-526] Move new token handling to FirebaseMessagingService

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java

The error message may be null so we pass the exception itself instead
Fixes #126

[MOB-580] Fix a possible NullPointerException in getAdvertisingId

---

iterableapi-ui/src/main/java/com/iterable/iterableapi/ui/BitmapLoader.java
iterableapi/src/main/java/com/iterable/iterableapi/util/Future.java

+ check if an ImageView is attached when updating with a bitmap
Future was holding weak references to callbacks, and they were garbage collected. It is holding strong references instead + we check if the imageView is still attached to the window when updating it with the fetched bitmap.

[MOB-688] Fix inbox image loading

---

iterableapi-ui/src/main/java/com/iterable/iterableapi/ui/inbox/InboxFragment.java
iterableapi-ui/src/main/java/com/iterable/iterableapi/ui/inbox/InboxRecyclerViewAdapter.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppMessage.java

`DiffUtil` is comparing objects within arrays, but since the in-app messages themselves are mutable, we were effectively comparing the updated `IterableInAppMessages` to themselves. This PR changes `InboxRecyclerViewAdapter` to use an immutable `InboxRow` class instead.

[MOB-689] Fix read/unread state update

---

iterableapi-ui/src/main/java/com/iterable/iterableapi/ui/inbox/InboxRecyclerViewTouchHelper.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppDeleteActionType.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java

The inbox-Swipe-Left keyword is now changed to inbox-swipe making it more generic for app developers. This will remove the constraints/future confusion in case customer wants to implement deletion of message using different swipe methods.

MOB-703 Change trackInAppConsume parameter

---

iterableapi-ui/src/main/java/com/iterable/iterableapi/ui/inbox/InboxActivity.java
iterableapi-ui/src/main/java/com/iterable/iterableapi/ui/inbox/InboxFragment.java
iterableapi-ui/src/main/java/com/iterable/iterableapi/ui/inbox/InboxMessageActivity.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppManager.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableLogger.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableRequest.java

Added method in Iterable Logger to have verbose implementation.
Added a generic method to callout from any Iterable class to understand from which class, method and line number the call is made.
Called the generic functions from few of Iterable API's key functionality like trackInAppOpen, trackInAppClose, showMessage, inappClose etc enabling developers to understand the internal flow of SDK
Added IterableLog statements to Log Request and Response with proper indentation for JSON objects.

MOB 706 Improve Logging in Android SDK

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppManager.java

A check is set where the 'consume' parameter is set to true only if the call is made from InApp location. Else (in case of inbox), the consume flags to false.

MOB 806 Call consume only if inapplocation is inapp

---

iterableapi-ui/src/main/java/com/iterable/iterableapi/ui/BitmapLoader.java

Log appropriate error when an empty url is obtained from inbox item thumbnail parameter

[MOB-904] Handle Empty Thumbnail URL

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java

These methods were originally added for debugging purposes and they should not be in the SDK.

[MOB-907] Remove sendPush methods

---

iterableapi-ui/src/main/java/com/iterable/iterableapi/ui/inbox/IterableInboxFragment.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableInboxSession.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java

This architecture is good in terms of scaling. Also enabling other developers to play with sessionId if they end up not using the IterableInboxFragment altogether.
I tried minimizing, switching back and forth the inbox fragment, things are working. But in certain combination, the sessionId was not generated which I will have to check properly.
One thing to note is that the bug where we are not sending appropriate inapp location needs to be fixed for sessionIds to be sent during the request. Currently only in-app consume and trackSession are able to send sessionIds

[MOB-926] add session id to inbox calls

---

.travis.yml

emulator-headless has been removed in 29.2.11:
https://androidstudio.googleblog.com/2019/12/emulator-29211-and-amd-hypervisor-12-to.html

[MOB-991] Travis: fix build compatibility with emulator 29.2.11 by using 29.2.1 instead

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppHTMLNotification.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java

The location variable was introduced in this class as a fix to previous bug MOB 965. Using the same variable to send the current location while inApp is getting closed.

[MOB-974] Bug fix. Send inbox as an inapp location for trackInAppClose

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFileStorage.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableInAppFileStorageTest.java

The in app load will now look for file directory. If it does not exist (which will occur during the first launch after new SDK migration), the inapp json will be loaded from cache directory and subsequent metadata changes will be saved in file directory.

[MOB-914] Read Write in-app json on persistent file directory

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppHTMLNotification.java

getSize returns the screen size minus the navigation bar, which is what we want

Use the proper screen height value when resizing an in-app message

---

.travis.yml

Google has fixed the emulator so we can keep using the latest

[MOB-1050] Remove emulator workaround from Travis CI

---

iterableapi/src/test/java/com/iterable/iterableapi/IterableInboxTest.java
iterableapi/src/test/resources/inapp_payload_inbox_multiple.json

Added inbox parameter to constructor. Default read status will be false unless specified in json obtained from server.
One message in json file used for testing updated to have read status as true.
One Test method updated and one test method added to verify the functionality.

[MOB-1006] Add support for 'read' flag from getMessages API

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterablePushRegistration.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java
iterableapi/src/test/java/com/iterable/iterableapi/IterablePushRegistrationTest.java

These methods have been deprecated since 3.0.0, it's time to remove them.

[MOB-1190] Remove deprecated push registration methods

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationHelper.java

It was working but was logging this error message every time: `android.content.res.Resources$NotFoundException: String resource ID #0x0.`
We should not be trying to get resource ID 0.

[MOB-1124] Don't log an error when notification channel name is not set

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppDisplayer.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java

Globally saves urlCallBack and location.
Retains if the view is going to reload. If not, it will assign the stored variable to null.

[MOB-1157] - Retain data during configuration change

---

iterableapi-ui/src/main/res/layout/iterable_inbox_item.xml

There is no padding at the bottom of the Inbox cell (after the date text view), which makes it look weird when combined with other kinds of cells. Need to add at least a few px of padding there.

[MOB-1223] Add padding at the bottom of the Inbox cell

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppHTMLNotification.java

In App tries to resize but leads to failure throwing an exception. Assigning notification to null so that next launches can detect null and initialize it properly.

[MOB-1228]- Quick Fix for inapp notification

---

iterableapi-ui/src/main/java/com/iterable/iterableapi/ui/inbox/IterableInboxActivity.java

Also mirroring iOS functionality. You can pass the activity title like this when launching `IterableInboxActivity`:
```kotlin
val intent = Intent(context, IterableInboxActivity::class.java)
intent.putExtra("activityTitle", "My Inbox")
startActivity(intent)
```

[MOB-1229] Add an option to specify activity title for Inbox

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java

onStart method gets invoked as the app comes to foreground and we set layout to take window size. I dont know how it did perform without any issue in Dialog previously but removing that code seems to resolve the issue.

[MOB-1255] - Dialog fragment losing constraints

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java

Added a check inside oncreate to see if saved bundle contains information about trackInAppOpen.

[MOB-1219] - Prevent redundant trackinapp calls

---

sample-apps/inbox-customization/app/build.gradle
sample-apps/inbox-customization/build.gradle

It's pulling the SDK from Jitpack, no need for that anymore.

[MOB-1277] Switch the sample app to the release version of the SDK

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java

A new method which now accepts subscribedMessageTypeIds, campaignId and templateId for updateSubscription call. Resolves feature parity on iOS and Android.

[MOB-1286] - support new parameters for update subscription api call

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableRequest.java

OkHttp bundled with some Android versions has bugs that result in exceptions. We need to catch these so they can't crash the app.

[MOB-1363] Catch all exceptions in IterableRequest

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableUtil.java
iterableapi/src/main/java/com/iterable/iterableapi/util/IOUtils.java

Hi!
While using the SDK, we noticed when using StrictMode that these streams weren't being closed. So I thought that we should patch it.

Close streams after reading file

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java

* Hide the webView instead of DecorView for compatibility with API 29+
* Show the dialog when the WebView is fully loaded, or after 500 ms, whichever happens earlier

[MOB-1424] InAppFragment improvements, delayed display

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableLogger.java

PrintInfo method internally uses system level log instead of using IterableLogger. This bypasses the Iterable's config value.
The fix:  use IterableLogger. It will print only when VERBOSE is set in config.
Closes #235

[MOB-1713] - Update IterableLogger

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java

Email and UserID can be null. In this situation, all the users using the device token will be disabled according to the backend docks. Also ReactNative will be having seperate methods to disableAllUsers and disableSpecific users. This will enable it too.

[MOB-1754] - Disable Device for all users

---

iterableapi/src/androidTest/AndroidManifest.xml
iterableapi/src/main/res/values/strings.xml
iterableapi/src/test/AndroidManifest.xml

This avoids consumer apps accidentally
inheriting/overriding IterableAPI app_name.
https://github.com/Iterable/iterable-android-sdk/issues/242

Remove strings.xml from iterableapi.

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppDisplayer.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java

These must happen under weird circumstances, since I'm not sure how it can get to that state.
This is just an immediate fix. In the future we should look at how to make it more resilient (how to keep the callback).
Fixes #241.

[MOB-1823] Fix NullPointerExceptions in IterableInAppFragmentHTMLNotification

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java

Calling other trackInAppMethod as a fallback method in case we fail to get message corresponding to the messageId.

[MOB-1868] - handle trackInAppClick on deleted Message

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationHelper.java

Fixes #250.
`getString` was logging warnings when a string resource was provided via `android:resource`. This changes the code a bit so we don't call `getString`/`getInt`. The logic is still the same.

[MOB-1910] Resolve channel name as a string resource without logging warnings

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppManager.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableInAppManagerTest.java

A lock on processing and showing messages which will be checked along with other checks when processing the messages. The lock when set to false will trigger scheduleProcessing.

[MOB-1894] - In App Locks

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java

Added a check if message is null in case the message gets deleted in the background and gets synced with the app.

[MOB-2234] - Fix for SDK Crash on inapp close

---

iterableapi/src/main/java/com/iterable/iterableapi/IterablePushActionReceiver.java

This doesn't really happen on real devices, only when bots try to hack the apps with the SDK. But it creates noise in crash reports, so it's worth fixing.

[MOB-2123] Handle extras == null in IterablePushActionReceiver

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppMessage.java

1. Checking for context, dialog and window in case the orientation changes and those get destroyed
2. Making the inapp displaysettings final so that even if it is public, its not changed at a later stage.

[MOB-2309] - Fix for In App Crash

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableFirebaseMessagingService.java
iterableapi/src/main/java/com/iterable/iterableapi/IterablePushActionReceiver.java

Currently, we require that `IterableApi.initialize` is always called in `Application#onCreate`. However, there is no easy way to do that in React Native. This adds support for late initialization of the SDK with two changes:
* Push actions: If SDK is not initialized by the time we receive a push action, it is stored in a static variable and executed after SDK init
* Silent push messages are skipped if (we're going to refresh the in-app queue on launch anyway, so skipping these should be fine)

[MOB-2270] Support delayed initialization

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/test/java/com/iterable/iterableapi/BasePowerMockTest.java
iterableapi/src/test/java/com/iterable/iterableapi/BaseTest.java
iterableapi/src/test/java/com/iterable/iterableapi/DeferredDeepLinkTest.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableActivityMonitorTest.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableApiAuthTests.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableFirebaseMessagingServiceTest.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableInAppFileStorageTest.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableInAppManagerSyncTest.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableInAppManagerTest.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableInboxTest.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableNotificationTest.java
iterableapi/src/test/java/com/iterable/iterableapi/IterablePushRegistrationTest.java

This only removes some of them; `ApiClient` split is required to remove the others, so I'll do that there.

[MOB-2341] Refactor tests to not depend on partial mocks

---

iterableapi/src/test/java/com/iterable/iterableapi/IterableApiIntegrationTest.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java

There is an asynchronous gotcha in the way we disable tokens: getting a token is an asynchronous operation, and by the time we retrieve the token, email/userId might've changed. So we pass the current email/userId/authToken directly to the token registration/disable action so we use the correct user identifier even if the current one is different.
We didn't have integration tests covering this, and this adds one.

[MOB-2380] Add an integration test for disabling token

---

iterableapi/build.gradle

Failed CI runs would previously only display limited information, pointing to the line of code in question, but not showing the full backtrace or the error message. This enables extended logging, so we should get more details, like what was expected and what was received for `assertEquals`, etc.

[MOB-2390] Enable extended exception logging in unit tests

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableConfig.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java

https://iterable.atlassian.net/browse/MOB-2411
1.  Added offlineProcessing boolean flag in config defaulted to false.
2. Added setRequestProcessor method in apiClient for IterableApi to be able to set offline mode after/during initializaiton.
3. In IterableAPI, if the flag is true, setRequestProcessor to offline.
Consequence: Had to make apiClient static and its required authProvider static as well.

[MOB-2411] - Offline flag in config

---

iterableapi/src/main/AndroidManifest.xml
iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableNetworkConnectivityManager.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableTaskRunner.java
iterableapi/src/main/java/com/iterable/iterableapi/OfflineRequestProcessor.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableTaskRunnerTest.java

https://iterable.atlassian.net/browse/MOB-2152
1. Created NetworkConnectivity Manager: One place to have all out network related work. Made it with interface so other modules can subscribe to it and listen to network events
2. TaskRunner now implements ConnectivityManager interfaces too and calls RunNow function when onNetworkConnected callback is called.
3. ProcessTask function will check for networkConnectivity before processing and deleting the task
4. ConnectivityManager's lifecycle will start with initialization of OfflineRequestProcessor and will remain shared instance
5. Changes in Test method to accompany networkConnectivityMonitor in task runner
6. Pending work: What if device is below LOLLIPOP? What should the networkManager should do?

[MOB-2152] - Offline Network Monitoring

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java

https://iterable.atlassian.net/browse/MOB-2371
Calling IterableTaskStorage.deleteAlltasks in IterableApi's onlogout method when offline processing is enabled.

[MOB - 2371] - Delete all tasks on log out

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java
iterableapi/src/main/java/com/iterable/iterableapi/IterablePushRegistrationTask.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableApiIntegrationTest.java
iterableapi/src/test/java/com/iterable/iterableapi/IterablePushRegistrationTaskTest.java

* [MOB-2433](https://iterable.atlassian.net/browse/MOB-2433)
The code was checking for the presence of a Firebase database URL, that is not directly necessary for push to work. This PR changes the check to get the FCM sender id, that is actually necessary for push and is a better indicator of FCM being set up correctly.

[MOB-2433] Fix Firebase check to work without a Firebase database URL

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableNetworkConnectivityManager.java

https://iterable.atlassian.net/browse/MOB-2476
Added synchronized keyword to add and remove listeners so that regardless from which thread the listeners are added or removed, while the listeners are being iterated over, they will have lock over the array.

[MOB-2476] - Making NetworkManager threadsafe

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java

https://iterable.atlassian.net/browse/MOB-2437
Get remote configuration for offline mode.
1. Call get remote configuration when app comes to foreground. Should ideally call it during initialization But existing tests are failing.
2. On Success -> call the setOfflineProcessingEnabled
3. A type check to NOT reassign and reinitialize similar request processor.

[MOB-2437] - Get Remote Configuration

---

iterableapi/src/androidTest/java/com/iterable/iterableapi/IterableApiRequestsTest.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableRequestTask.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableTask.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableTaskRunner.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableTaskStorage.java

https://iterable.atlassian.net/browse/MOB-2417
1. Changed date type from Date to long to store unix epoch time in milliseconds
2. Added sentAt dates in headers
3. Added check in test method to see if sentAt is sent in headers for all the requests
4. Added method in taskRunner to add createdAt in json data when making request back from database.
Pending -> Test method to see if createdAt is present in offline requests.

[MOB - 2417] - CreatedAt and SentAt in requests

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableConfig.java
iterableapi/src/main/java/com/iterable/iterableapi/OfflineRequestProcessor.java
iterableapi/src/main/java/com/iterable/iterableapi/OnlineRequestProcessor.java
iterableapi/src/main/java/com/iterable/iterableapi/RequestProcessor.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java

https://iterable.atlassian.net/browse/MOB-2541
1. Removed offlineProcessing flag from IterableConfig
2. New interface method `onLogout(context)` introduced in `RequestProcessor`
3.  `apiClient` now has onLogout() method which makes calls to its requestProcessor's `onLogout(context)`
4. `IterableAPI` calls `onLogout()` of `apiClient`
5. Updated test method to check if database is cleared by calling fetch remote configuration.

[MOB - 2541] - Remove offline configuration from IterableConfig

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableRequestTask.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableTaskRunner.java
iterableapi/src/main/java/com/iterable/iterableapi/OfflineRequestProcessor.java

https://iterable.atlassian.net/browse/MOB-2548
1. Added new enum ProcessorType in `IterableApiRequest`
2. Added the field in `IterableConstants`
3. Added a setter for processing type. If setter is not used, it will be defaulted to Online Processing.
4. All the cascading changes to other classes - Now offline processor's get and post request uses this setter before executing the request. Also same changes for TaskRunner where it fetches the task from database and executes the request.

[MOB-2548] - send SDK Request Processor in Header

---

iterableapi/src/main/java/com/iterable/iterableapi/OfflineRequestProcessor.java

https://iterable.atlassian.net/browse/MOB-2553
getMessages and getRemoteConfiguration were reporting Offline as their request processor. Updated all the get request in Offline Request processor to label as Online as no DB operation is involved

[MOB - 2553] - Get Request Processor Type - Online

---

app/src/androidTest/java/com/iterable/iterableapi/MainActivityTest.java
app/src/androidTest/java/com/iterable/iterableapi/testapp/InboxUITest.java
app/src/test/java/com/iterable/iterableapi/InboxUITest.java
iterableapi-ui/src/main/java/com/iterable/iterableapi/ui/inbox/IterableInboxActivity.java
iterableapi-ui/src/main/java/com/iterable/iterableapi/ui/inbox/IterableInboxFragment.java
iterableapi-ui/src/main/res/layout/iterable_inbox_fragment.xml
iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java

https://iterable.atlassian.net/browse/MOB-2585
1. When passed with title and text in bundle, IterableInboxFragment can take that text and override default title and message text
2. Visibility are toggled based on inbox count on every update
3. Inbox Fragment XML now has two text views kept inside RelativeLayout beside recyclerView instead of just having RecyclerView
4. If inbox is displayed using `IterableInboxAcitivity` instead of `IterableInboxFragment`, we still relay the bundle arguments to `IterableInboxFragment` internally. So bundle passed to `IterableInboxActivity` will still work.
5. Added test method to see if passed texts are actually displayed on inbox screen.

[MOB-2585] - No message view for inbox

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableRequestTask.java

https://iterable.atlassian.net/browse/MOB-2680
Increased timeout for get calls to 10seconds.

[MOB-2680] - Increase timeout for get calls

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java

https://iterable.atlassian.net/browse/MOB-2656
1. Allowing dismiss with state loss.
This allows the inapp to be dismissed in background without crashing, after the app is minimized. Dismiss after app background happens in attempt to achieve smooth dismiss animation.
Resolves the github issue - https://github.com/Iterable/iterable-android-sdk/issues/322

[MOB - 2656] - InApp Dismiss to allow stateloss

---

.gitignore
iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppManager.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableInAppManagerTest.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableInAppMessageTest.java
iterableapi/src/test/resources/inapp_payload_inbox_read_state_1.json
iterableapi/src/test/resources/inapp_payload_inbox_read_state_2.json

* [MOB-2606](https://iterable.atlassian.net/browse/MOB-2606)
* adds SDK support for persisting read state per user rather than local device only

[MOB-2606] persistent read state for inbox in-apps

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppManager.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableInAppManagerTest.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableInboxTest.java
iterableapi/src/test/resources/inapp_payload_inbox_show.json
iterableapi/src/test/resources/inapp_payload_single.json

https://iterable.atlassian.net/browse/MOB-2762
1. Dont show inapp (process message) right on switching to foreground. Wait for sync to happen and it will trigger scheduleProcessing automatically.
2. Schedule Processing is manually called if the app comes to foreground within 60 seconds of its last sync.
3. Schedule processing is also called when getMessage call fails. It compensates for network being offline

[MOB-2762] - Bug fix - In App read state

---

CHANGELOG.md
iterableapi-ui/build.gradle
iterableapi/build.gradle
sample-apps/inbox-customization/app/build.gradle

https://iterable.atlassian.net/browse/MOB-2653
Preparing to release `3.3.0-beta3`

Prepare for 3.3.0-beta3

---

app/build.gradle
iterableapi/build.gradle

* [MOB-2791](https://iterable.atlassian.net/browse/MOB-2791)
19.0.0 was released in June 2019 and is the first version migrated to AndroidX. We’re already using AndroidX, so it makes sense to require at least version 19.0.0.
This also raises `minSdkVersion` to 16, which is the minimum supported by `firebase-messaging`.

[MOB-2791] Update firebase-messaging dependency to 19.0.0

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java

* [MOB-2790](https://iterable.atlassian.net/browse/MOB-2790)
`getInAppMessages` and `spawnInAppNotification` (which does nothing) has been deprecated for a long time. It should be safe to make one package-private (for further changes) and remove the other.

[MOB-2790] Remove deprecated in-app methods

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableConfig.java
iterableapi/src/main/java/com/iterable/iterableapi/IterablePushRegistrationTask.java
iterableapi/src/test/java/com/iterable/iterableapi/IterablePushRegistrationTaskTest.java

* [MOB-2789](https://iterable.atlassian.net/browse/MOB-2789)
`IterableConfig.legacyGCMSenderId` was used for GCM → FCM migration that happened 2 years ago. At this point, most likely no one is using it, and everyone migrated to FCM long time ago.

[MOB-2789] Remove legacyGCMSenderId

---

iterableapi/build.gradle
iterableapi/src/main/java/com/iterable/iterableapi/IterableFirebaseMessagingService.java
iterableapi/src/main/java/com/iterable/iterableapi/IterablePushRegistrationTask.java

https://iterable.atlassian.net/browse/MOB-2912
1. Upgrading firebase to 20.3.0 to use FirebaseMessaging instead of FirebaseInstanceId to get Token.
2. Updated related methods.

[MOB-2912] - Firebase Crash Fix

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java

https://iterable.atlassian.net/browse/MOB-2971
This method `setContext` will be called from RN Android Application class to just keep context ready with Iterable. This way, by the time IterableSDK is initialized and starts processing request, IterableActivitymonitor will already be aware of activities on the screen.

[MOB-2971] - Set Context method

---

build.gradle
iterableapi-ui/build.gradle
iterableapi/build.gradle

https://iterable.atlassian.net/browse/MOB-2939
- Removes residual tasks and code from build.gradle file left from our Jcentre/Bintray to Maven migration.

[MOB - 2939] - Remove bintray reference

---

iterableapi-ui/build.gradle
iterableapi/build.gradle

https://iterable.atlassian.net/browse/MOB-3238
This was removed in its last iteration during the clean up of bintray related files. But looks like we need it as part for performing ./gradlew install command.
NOTE:
This is the place from where gradle gets definition of `install`:
https://raw.githubusercontent.com/nuuneoi/JCenter/master/installv1.gradle
This task generates pom file.
Most of the content looks similar to our existing script in [maven-push.gradle](https://github.com/Iterable/iterable-android-sdk/blob/ffabfe74a087bc9721bc18a1a9429ddcaf0481fb/maven-push.gradle#L56-L101) file, which also generates pom file.

[MOB-3238] - Add missing install script in build.gradle

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationHelper.java

https://iterable.atlassian.net/browse/MOB-3266
Check for Build version if its >=17, use the API setShowWhen(Boolean variable) to show timestamp.
Reference: https://developer.android.com/reference/android/app/Notification.Builder#setShowWhen(boolean)
Can remove the check once minimum version of SDK is set to >=17

[MOB-3266] - Timestamp on notification

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppManager.java

https://iterable.atlassian.net/browse/MOB-3091
This is fix suggested in review: https://github.com/Iterable/react-native-sdk/pull/174. This way RN Android wont need any change.
syncInApp() is called right after InAppManager is initialized. SyncInApp call when switching to foreground remains unaffected. Duplicate calls will also be not made as lastSyncTime is updated inside SyncInApp call.

[MOB-3091] - Sync In App after initialization

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationHelper.java

For issue
https://github.com/Iterable/iterable-android-sdk/issues/377
Resolve following error for Android 12
```
java.lang.IllegalArgumentException: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
at android.app.PendingIntent.getBroadcast(PendingIntent.java:632) …
```

Android 12: Set flag PendingIntent.FLAG_IMMUTABLE

---

iterableapi-ui/src/main/AndroidManifest.xml
iterableapi/src/test/AndroidManifest.xml

https://iterable.atlassian.net/browse/MOB-3271
Adding "exported: false" to InboxActivity and InboxMessageActivity.
Service - Firebase already had this flag.
This flag indicates whether the given application component is available to other applications. If false, it can only be accessed by same package. If true, it can be invoked by external entities.

[MOB - 3271] - xml changes for Android 12

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableAuthManager.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableLogger.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableRequestTask.java

(https://iterable.atlassian.net/browse/MOB-XXXX)](https://iterable.atlassian.net/browse/MOB-3703)
1. Removed logging of JWT keys and API keys from Headers and also from error case scenarios. 
2. Added checks to leverage config.loglevel only if App is in debug mode.

[MOB - 3703] - Sensitive log information

---

app/src/androidTest/java/com/iterable/iterableapi/MainActivityTest.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableWebView.java

* [MOB-3767](https://iterable.atlassian.net/browse/MOB-3767)
* disallows JS execution within the web view of an in-app

[MOB-3767] set in-app javascript execution to false

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationBuilder.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationHelper.java

Fix for PR - https://github.com/Iterable/iterable-android-sdk/pull/411
Uses sharedInstance.config.allowedProtocols

Test Fix for PR - Allowed Protocols

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableActionRunner.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableDeeplinkManager.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppManager.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableUtil.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableInAppManagerSyncTest.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableInAppManagerTest.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableInboxTest.java
iterableapi/src/test/java/com/iterable/iterableapi/IterablePushActionReceiverTest.java

[* [MOB-XXXX](https://iterable.atlassian.net/browse/MOB-XXXX)](https://iterable.atlassian.net/browse/MOB-3850)
1. InAppManager no more holds array of allowedProtocols. Its always accessed from IterableConfig.
2. `isUrlOpenAllowed` is now a common utility method in IterableUtil
3. Modified test methods to accomodate the changes

Mob 3850 patch for allowed protocols

---

iterableapi/src/androidTest/java/com/iterable/iterableapi/IterableApiDeeplinkTest.java
iterableapi/src/androidTest/resources/push_payload_action_buttons.json
iterableapi/src/main/java/com/iterable/iterableapi/IterableActionRunner.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableConfig.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableDeeplinkManager.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppManager.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableInAppManagerSyncTest.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableInAppManagerTest.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableInboxTest.java
iterableapi/src/test/java/com/iterable/iterableapi/IterablePushActionReceiverTest.java
iterableapi/src/test/resources/push_payload_action_buttons.json

* [MOB-3769](https://iterable.atlassian.net/browse/MOB-3769)
* implements `allowedProtocols` into `IterableConfig` and makes sure that links that aren't `https` or in that list are not opened by the SDK

[MOB-3769] allowed protocols

---

CHANGELOG.md
iterableapi-ui/build.gradle
iterableapi/build.gradle
sample-apps/inbox-customization/app/build.gradle

[* [MOB-3851](https://iterable.atlassian.net/browse/MOB-XXXX)](https://iterable.atlassian.net/browse/MOB-3851)
Prepare to release 3.4.0

MOB-3851 - Prepare for 3.4.0

---

iterableapi/src/main/AndroidManifest.xml
iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationBuilder.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationHelper.java
iterableapi/src/main/java/com/iterable/iterableapi/IterablePushActionReceiver.java
iterableapi/src/main/java/com/iterable/iterableapi/IterablePushNotificationUtil.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableTrampolineActivity.java
iterableapi/src/main/java/com/iterable/iterableapi/TrampolineActivity.java
iterableapi/src/main/res/values/styles.xml

[[MOB-3754]](https://iterable.atlassian.net/browse/MOB-3754)
1. Introduced new Activity - `IterableTrampolineActivity` with transparent style which now replaces `IterablePushActionReceiver` as a starting point when user taps notification replacing.
2. Notification Builder creates PendingIntent from `getActivity` instead of `getBroadcast` to accommodate to above change. [Except for custom action with openApp false]
3. Data from notification is thus, now routed through `IterableTrampolineActivity `
4. ~~`IterableTrampolineActivity ` passes the data as is to `IterablePushActionReceiver` and dismisses itself`~~
5. `IterablePushActionReceiver` is still applicable for those actions which invoke custom actions with openApp flag unchecked. `IterableTrampolineActivity` will not be invoked in this …

[MOB - 3754] - Handling Trampoline Restriction

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationBuilder.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationHelper.java

* #377
After deploying iterable SDK 3.4.0 with the Kiva Android app, I noticed [Android 12 specific crashes](https://github.com/Iterable/iterable-android-sdk/issues/377#issuecomment-1006741121) in our crash logging caused by a missing PendingIntent flag. 
It appears as if the fixes for this issue in previous releases (https://github.com/Iterable/iterable-android-sdk/pull/380 and https://github.com/Iterable/iterable-android-sdk/pull/390) regressed in SDK 3.4.0 (a278c7d773a62a1e356ac47263b4e12bea2373d7), as the change to these files was not called out as intentional in https://github.com/Iterable/iterable-android-sdk/pull/413.
I restored both [IterableNotificationBuilder.java](https://github.com/Iterable/iterable-android-sdk/blob/master/iterableapi/src/main/java/com/iterable/iterableapi/Iter …

[Issue #377] Android 12: Set flag PendingIntent.FLAG_IMMUTABLE

---

iterableapi/src/test/java/com/iterable/iterableapi/IterableNotificationTest.java

* [MOB-3897](https://iterable.atlassian.net/browse/MOB-3897)
Add a test to make sure `PendingIntent.FLAG_IMMUTABLE` is present in both the content intent and action (button) intents to prevent any future regressions due to this flag being missing.

[MOB-3897] Add regression test for PendingIntent.FLAG_IMMUTABLE

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationHelper.java

Adds the NO_BADGE flag in a single place so we aren't defining the channelId in different locations.

Refactor channel naming

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationHelper.java

* [MOB-3970](https://iterable.atlassian.net/browse/MOB-3970)
1. When creating a notification, its checked whether a channel is created for current configuration.
2. If not, a channel is created. If opted for no badges, we create a channel with id -> package name_noBadge
3. Old configuration channel, if exists is removed if no active notification for that channel exists.

[MOB-3970] - Notification Badge through Android Manifest

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java

* [MOB-4068](https://iterable.atlassian.net/browse/MOB-4068)
For JWT enabled projects using Android SDK, a logout and login ends up disabling the user but not registering the user again(stopping them from getting push notification). Reason being the auth not reset because the authHandler kept returning the same authtoken and was not set again. Instead it should be set to null and then next time user logs in, the code can continue normally

[MOB-4068] - Reset jwtToken when logging out

---

iterableapi/src/main/AndroidManifest.xml

* [MOB-4026](https://iterable.atlassian.net/browse/MOB-4026)
> 1. `singleInstance` launchmode of TrampolineActivity did not allow for parent activity to show in recent apps after destorying itself. Setting it to `singleTop` allows it.

[MOB - 4026] Fix - App not visible in recent apps

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableUtil.java

* [MOB-4447](https://iterable.atlassian.net/browse/MOB-4447)
> The list of protocols doesn't work on mParticle because it creates a new instance.
Changes the reference to use the shared instance.

[MOB-4447] feature/MOB-4447-protocol-fix

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableAuthHandler.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableAuthManager.java

* [MOB-4641](https://iterable.atlassian.net/browse/MOB-4641)
1. Added Success and Failure method to AuthHandler interface.
2. SuccessCallback is called when SDK receives the `authToken`. The success callback passes back the received authToken which developers can verify to see if its the correct one.
3. Failure callback is called when nothing is returned with possible throwable object which can be useful to understand the cause.

[MOB-4641] - Add success and failure callback to AuthHandler

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFileStorage.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppMemoryStorage.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppStorage.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableUtil.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableUtilImpl.java
iterableapi/src/test/java/com/iterable/iterableapi/BaseTest.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableUtilRule.java

* [MOB-4852](https://iterable.atlassian.net/browse/MOB-4852)
* split out `IterableUtil`
* reorganizes some other files
* no functional changes

[MOB-4852] reorganization

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableConfig.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppManager.java

* [MOB-4666](https://iterable.atlassian.net/browse/MOB-4666)
* adds an `IterableConfig` option to switch between storing on file (as before, and still default) or just in memory

[MOB-4666] in apps config memory

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableNetworkConnectivityManager.java

* [MOB-3876](https://iterable.atlassian.net/browse/MOB-3876)
`connectionManager.registerNetworkcallback` can throw Security exception on non Pixel device unless the manufacturer's fix it
Reference :https://issuetracker.google.com/issues/175055271
Until then, this try catch should avoid app crashes.

[MOB-3876] - Try catch around network callback

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationHelper.java
iterableapi/src/main/java/com/iterable/iterableapi/IterablePushRegistrationTask.java

* [MOB-5365](https://iterable.atlassian.net/browse/MOB-5365)
This pull request updates the custom sound to be set at the notification channel rather than at the notification builder. See [here](https://developer.android.com/reference/android/app/NotificationChannel#setSound(android.net.Uri,%20android.media.AudioAttributes)) for the documentation. This resolves a part of the issue, but further logic needs to be implemented to address the situation for when the custom sound is updated for the push notification template.
[MOB-5365]: https://iterable.atlassian.net/browse/MOB-5365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-5365] update to set custom sound at notification channel

---

iterableapi/build.gradle
iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationHelper.java

* [MOB-5406](https://iterable.atlassian.net/browse/MOB-5406)
This pull request provides unique notification channels for each sound sent from the Iterable UI. There are checks to provide the default sound for edge cases provided by the custom sound box on the UI. The UI may be changed in the future to not except these edge cases.
[MOB-5406]: https://iterable.atlassian.net/browse/MOB-5406?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-5406] create notification channel for each sound

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationHelper.java

* [MOB-5664](https://iterable.atlassian.net/browse/MOB-5664)
> Revert the code where the channel name was derived by reading value from Android Manifest. If not value is found, a default name "iterable channel" is provided. Now, with custom sound, if a soundURI exists from a provided custom sound, only then soundName is treated as a channel name. Otherwise, old way of handling the name still persists.
[MOB-5664]: https://iterable.atlassian.net/browse/MOB-5664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-5664] - Revert channel name implementation

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableAuthManager.java

* [MOB-5874](https://iterable.atlassian.net/browse/MOB-5874)
>Schedule a 10 second auto refresh for auth handler if auth token is found null when initializing. Also, when authHandler receives a authToken from handler in its handler, a similar null check will schedule 10 second refresh throwing a onTokenRegistrationFailure. This callback should allow them to refresh authToken.
[MOB-5874]: https://iterable.atlassian.net/browse/MOB-5874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB - 5874] - Schedule auth refresh when auth null

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedManager.kt

* [MOB-5989](https://iterable.atlassian.net/browse/MOB-5989)
This pull request removes the redundant embedded manager call from the IterableApi class and removes the test function to get embedded messages from a test JSON response from the embedded manager.
[MOB-5989]: https://iterable.atlassian.net/browse/MOB-5989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-5989] remove redundant embedded manager call

---

.github/workflows/jira.yml

Create an issue in Iterable's Jira when an issue is opened on GitHub

create issue in jira when github issue opened

---

CHANGELOG.md
iterableapi-ui/build.gradle
iterableapi/build.gradle
sample-apps/inbox-customization/app/build.gradle

* [MOB-6134](https://iterable.atlassian.net/browse/MOB-6134)
> Prepare for 3.5.0-alpha2
[MOB-6134]: https://iterable.atlassian.net/browse/MOB-6134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-6134] - Prepare for 3.5.0-alpha2

---

app/build.gradle
iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableConfig.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppManager.java

[MOB-4666] in apps config memory
* [MOB-6164](https://iterable.atlassian.net/browse/MOB-6164)
* Original ticket: [MOB-4666]: https://iterable.atlassian.net/browse/MOB-4666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Cherry picks #474 onto master branch
[MOB-6164]: https://iterable.atlassian.net/browse/MOB-6164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB - 6164] Merge pull request #474 from Iterable/jay/MOB-4666-in-apps-config-memory

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedManager.kt

* [MOB-6135](https://iterable.atlassian.net/browse/MOB-6135)
> Similar implementation to getInAppMessages where SDK initialization is checked before making a call to API
[MOB-6135]: https://iterable.atlassian.net/browse/MOB-6135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-6135] - Check SDK initialization before API call

---

iterableapi-ui/src/main/java/com/iterable/iterableapi/ui/inbox/IterableInboxFragment.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppManager.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableInboxTest.java

* [MOB-5730](https://iterable.atlassian.net/browse/MOB-5730)
* add callback for setRead/removeMessage
* modify test for setRead and added test for removeMessage
* fixes
* Update build.gradle
* removed resultcallbackhandler
* Update IterableInAppManager.java
* fixes
[MOB-5730]: https://iterable.atlassian.net/browse/MOB-5730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB 5730] Add callbacks to reading/removing in-app messages (#557)

---

iterableapi/src/main/java/com/iterable/iterableapi/EmbeddedImpressionData.kt
iterableapi/src/main/java/com/iterable/iterableapi/EmbeddedSessionManager.kt

* [MOB-6216](https://iterable.atlassian.net/browse/MOB-6216)
- Implements impression tracking listeners in the embedded session handler
- Associated changes to the tester app have been added and are located on the `embedded-session-tracking` branch
- The SDK currently prints a log statement when impressions start and end
- The next pull request will add the processing for this data
[MOB-6232]: https://iterable.atlassian.net/browse/MOB-6232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOB-6216]: https://iterable.atlassian.net/browse/MOB-6216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-6216] implement impression tracking listeners

---

iterableapi/src/main/java/com/iterable/iterableapi/EmbeddedSessionManager.kt

* [MOB-6425](https://iterable.atlassian.net/browse/MOB-6425)
This pull request updates the impression tracking naming to align with iOS SDK.
fun startSession()
fun endSession()
fun startImpression(messageId: String)
fun pauseImpression(messageId: String)
[MOB-6425]: https://iterable.atlassian.net/browse/MOB-6425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-6425] align impression tracking signatures

---

iterableapi/src/androidTest/java/com/iterable/iterableapi/IterableTestUtils.java
iterableapi/src/main/java/com/iterable/iterableapi/EmbeddedSessionManager.kt
iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableConfig.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedManager.kt
iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationHelper.java

* [MOB-6443](https://iterable.atlassian.net/browse/MOB-6443)
- removes polling logic and fetching timer
- makes syncMessages function public
- adds onSwitchToForeground and onSwitchToBackground callbacks to the embedded session manager
- removes setting auto fetching interval from config
[MOB-6443]: https://iterable.atlassian.net/browse/MOB-6443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-6443] remove polling logic and adds callbacks to embedded session manager

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedMessage.kt
iterableapi/src/test/java/com/iterable/iterableapi/IterableEmbeddedMessageTest.kt
iterableapi/src/test/resources/embedded_payload_no_buttons_no_text.json
iterableapi/src/test/resources/embedded_payload_no_custom_payload.json
iterableapi/src/test/resources/embedded_payload_no_elements_no_custom_payload.json
iterableapi/src/test/resources/embedded_payload_optional_elements_and_custom_payload.json

* [MOB-6587](https://iterable.atlassian.net/browse/MOB-6587)
This pull request updates the type of campaign id to an integer.
[MOB-6587]: https://iterable.atlassian.net/browse/MOB-6587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-6587] updates campaign id to int type

---

iterableapi/build.gradle
iterableapi/src/main/java/com/iterable/iterableapi/EmbeddedSessionManager.kt
iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedManager.kt

* [MOB-6490](https://iterable.atlassian.net/browse/MOB-6490)
* [MOB-6610](https://iterable.atlassian.net/browse/MOB-6610)
* [MOB-6605](https://iterable.atlassian.net/browse/MOB-6605)
This pull request includes the following:
- toggles off impression tracking call if there are no impressions to track
- updates message updated callback to align with iOS SDK
- updates naming of several items to align with iOS SDK
- renames getEmbeddedMessages to getMessages to align with iOS SDK
[MOB-6490]: https://iterable.atlassian.net/browse/MOB-6490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOB-6610]: https://iterable.atlassian.net/browse/MOB-6610?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOB-6605]: …

[MOB-6490] toggle off impression tracking if no embedded messages

---

iterableapi/src/main/AndroidManifest.xml

- Ensure `IterableTrampolineActivity` always launched to handle all notifications
- Reverts back to `launchMode="singleInstance"` to ensure that the activity is always launched
- Use `excludeFromRecents="true"` to ensure that the activity is not shown in the recent apps list
This originates from the current `launchModes` and `Intent` flags for `IterableTrampolineActivity`
When receiving a notification, the Iterable Android SDK builds up an `Intent` and stuffs it inside the notification. This intent is executed upon the user tapping the notification. This intent encapsulates the action to create a new Activity, `IterableTrampolineActivity`.
Without this code change, `IterableTrampolineActivity` will occasionally not be …

Ensure IterableTrampolineActivity always launched

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableConfig.java

* [NIL]
> Removing duplicate function introduced during merge

Removing duplicate function

---

iterableapi/build.gradle
iterableapi/src/main/java/com/iterable/iterableapi/IterableKeychain.kt

Continuation on 6865. Add on changes
1. Checking for Throwable which will collect both Exception and Error if at all Security library is crashing with a Error and not exception.
2. Updating the dependency to use latest alpha version. Alpha version 5 also seems to fix race condition during creation process. Reference - https://developer.android.com/jetpack/androidx/releases/security#1.1.0-alpha05
3. Added some warning logs if this situation arrives so developers can take some action if it occurs during debugging

Catching Error along with Exception

---

iterableapi/build.gradle
iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableConfig.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableKeychain.kt

* [MOB-6865](https://iterable.atlassian.net/browse/MOB-6865)
- Handles condition where IterableKeychain creation returns null to Iterable API. SDK will continue to process without crashing.
There will be no email fetched from sharedPreferences in this rare case. No email will be persisted and the app will have to setEmail/setUserId on every app session for it to have email in memory than having it persisted for consequent app sessions
- Fixed indentation on IterableKeychain file. Using cmd+l on Android Studio
- Added method description in IterableConfig class so developers have more context on what `setEncryptionEnforced` means
- getKeychain is now annotated @nullable for future kotlin migration purpose
Fixes - #616 
Fixes - #631 
[MOB-6865]: …

[MOB - 6865] - Keychain null crash fix

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedManager.kt

* [MOB-7186](https://iterable.atlassian.net/browse/MOB-7186)
> This pull request updates the embedded session manager to a private property with an associated getter. Also, renames embeddedManager() to getEmbeddedManager().
[MOB-7186]: https://iterable.atlassian.net/browse/MOB-7186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-7186] updates embedded manager calls

---

iterableapi/src/main/java/com/iterable/iterableapi/EmbeddedImpressionData.kt
iterableapi/src/main/java/com/iterable/iterableapi/EmbeddedSessionManager.kt
iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedPlacement.kt
iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedSession.kt
iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableEmbeddedPlacementTest.kt
iterableapi/src/test/resources/embedded_payload_no_buttons_no_text.json
iterableapi/src/test/resources/embedded_payload_no_custom_payload.json
iterableapi/src/test/resources/embedded_payload_no_elements_no_custom_payload.json
iterableapi/src/test/resources/embedded_payload_optional_elements_and_custom_payload.json

* [MOB-7218](https://iterable.atlassian.net/browse/MOB-7218)
> This pull request updates the endpoint to align with the backend changes. No updates to the payload, but will align with BE if any changes are necessary.
[MOB-7218]: https://iterable.atlassian.net/browse/MOB-7218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-7218] impression tracking rework

---

iterableapi/src/androidTest/java/com/iterable/iterableapi/IterableApiResponseTest.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableAuthManager.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableRequestTask.java

* [MOB-7154](https://iterable.atlassian.net/browse/MOB-7154)
> This pull request implements JWT retry logic. Credit: Omni-CG.
[MOB-7154]: https://iterable.atlassian.net/browse/MOB-7154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-7154] Implement JWT Retry Logic for Android SDK

---

CHANGELOG.md
iterableapi-ui/build.gradle
iterableapi/build.gradle
sample-apps/inbox-customization/app/build.gradle

* [MOB-7297](https://iterable.atlassian.net/browse/MOB-7297)
> This pull request prepares for the version 3.4.17.
[MOB-7297]: https://iterable.atlassian.net/browse/MOB-7297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-7297] prepares 3.4.17 release

---

iterableapi-ui/build.gradle
iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java

* [MOB-?](https://iterable.atlassian.net/browse/MOB-?)
> Fiterable app was throwing error as resource not found. Making the resource with full name is making it work. Probably would be helpful in all projects having such conflicts in finding the resource. Also bumping up the minSdkversion in api-ui

Full qualified name for style resource

---

CHANGELOG.md

> This pull request updates the change log for embedded GA release.

[MOB-XXXX] updates changelog

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableActionRunner.java

* [MOB-7611](https://iterable.atlassian.net/browse/MOB-7611)
> We've implemented a check to ensure the package manager is not null, preventing potential crashes.
[MOB-7611]: https://iterable.atlassian.net/browse/MOB-7611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Resolve error

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java

* [MOB-6916](https://iterable.atlassian.net/browse/MOB-6916)
> We have added a check for SDK initialization on the necessary method call to address the crash.
[MOB-6916]: https://iterable.atlassian.net/browse/MOB-6916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Check for SDK initialization

---

iterableapi-ui/build.gradle

* [MOB-6035](https://iterable.atlassian.net/browse/MOB-6035)
This pull request updates the Glide library to the latest stable release [4.16.0](https://github.com/bumptech/glide/releases/tag/v4.16.0).
[MOB-6035]: https://iterable.atlassian.net/browse/MOB-6035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-6035] upgrades Glide library to latest stable version

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableAuthManager.java

* [MOB-6832](https://iterable.atlassian.net/browse/MOB-6832)
> Prevents crash by checking if the three components of auth token are present before decoding the expiration time. If not the SDK will throw an Exception continuing with retry mechanism and invoking failure callbacks.
[MOB-6832]: https://iterable.atlassian.net/browse/MOB-6832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-6832] - AuthDecode crash fix

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java

* [MOB-8057](https://iterable.atlassian.net/browse/MOB-8057)
> Embedded messages to sync as soon as user log in completes
[MOB-8057]: https://iterable.atlassian.net/browse/MOB-8057?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB - 8057] - Bug Fix - Embedded Messages Sync

---

CHANGELOG.md
iterableapi-ui/build.gradle
iterableapi/build.gradle
sample-apps/inbox-customization/app/build.gradle

* [MOB-8054](https://iterable.atlassian.net/browse/MOB-8054)
> This pull request prepares for version 3.5.1 release.
[MOB-8054]: https://iterable.atlassian.net/browse/MOB-8054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-8054] prepare for version 3.5.1 release

---

iterableapi/src/androidTest/java/com/iterable/iterableapi/IterableApiRequestsTest.java
iterableapi/src/main/java/com/iterable/iterableapi/CommerceItem.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java

* [MOB-8226](https://iterable.atlassian.net/browse/MOB-8826)
> This pull request adds optional attribution info to the track purchase public function in `IterableApi`.
[MOB-8226]: https://iterable.atlassian.net/browse/MOB-8226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-8226] add attribution info to track purchase

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedManager.kt
iterableapi/src/test/java/com/iterable/iterableapi/IterableEmbeddedManagerTest.java
iterableapi/src/test/resources/embedded_payload_multiple_3.json
iterableapi/src/test/resources/embedded_payload_multiple_4.json

* [MOB-7646](https://iterable.atlassian.net/browse/MOB-7646)
> This pull request updates get messages call and the manager logic for diff messages update from the BE.
[MOB-7646]: https://iterable.atlassian.net/browse/MOB-7646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-7646] update processing logic for diff merge messages

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableAuthManager.java

* [MOB-8838](https://iterable.atlassian.net/browse/MOB-8838)
Sets pendingAuth to false; fixes flow that skipped onAuthTokenRequested()
https://github.com/Iterable/iterable-android-sdk/issues/741
[MOB-8838]: https://iterable.atlassian.net/browse/MOB-8838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-8838] set pendingAuth to false

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java

* [MOB-8948](https://iterable.atlassian.net/browse/MOB-8948)
> This pull request introduces a flag that indicates if a user is anonymous which determines if stored user id is cleared or not .
[MOB-8946]: https://iterable.atlassian.net/browse/MOB-8946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOB-8948]: https://iterable.atlassian.net/browse/MOB-8948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-8948] sets anonymous user

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableAuthManager.java

* [MOB-9078](https://iterable.atlassian.net/browse/MOB-9078)
> Reset timer and flags completely when logging out. Looks like the timers were cleared but the flag was still not flipped back to `false`.
 
Fixes #757
[MOB-9078]: https://iterable.atlassian.net/browse/MOB-9078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-9078] - Reset timer when logging out

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableApiMergeUserEmailTests.java

* [MOB-9280](https://iterable.atlassian.net/browse/MOB-9280)
This pull request adds a set user id call when an anonymous user is created. I needed to pull the set user id and set email logic from the tryMergeUser callbacks for the unit tests to work properly. I also think it cleans up the code quite a bit.
[MOB-9280]: https://iterable.atlassian.net/browse/MOB-9280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-9280] set anonymous user

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableConfig.java

* [MOB-9317](https://iterable.atlassian.net/browse/MOB-9317)
> This pull request returns default event threshold limit back to 100.
[MOB-9317]: https://iterable.atlassian.net/browse/MOB-9317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-9317] updates event threshold limit

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java
iterableapi/src/main/java/com/iterable/iterableapi/util/CriteriaCompletionChecker.java

* [MOB-9572](https://iterable.atlassian.net/browse/MOB-9572)
> This pull request includes refactoring of remaining criteria completion logic.
[MOB-9572]: https://iterable.atlassian.net/browse/MOB-9572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-9571] refactors evaluateTree

---

app/src/main/java/com/iterable/androidsdk/AnonTrackingTestActivity.java
iterableapi/src/main/java/com/iterable/iterableapi/AnonymousUserManager.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableAnonUserHandler.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableConfig.java

* [MOB-9638](https://iterable.atlassian.net/browse/MOB-9638)
> Add handlers for notifying customer app of a newly created Anon userid
[MOB-9638]: https://iterable.atlassian.net/browse/MOB-9638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MOB-9638 - Add handlers for notifying customer app of a newly created Anon userid

---

iterableapi/src/main/java/com/iterable/iterableapi/AnonymousUserManager.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java

* [MOB-10030](https://iterable.atlassian.net/browse/MOB-10030)
> This pull request clears the user update object when consent is toggled.
[MOB-10030]: https://iterable.atlassian.net/browse/MOB-10030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-10030] clears user update storage when consent is toggled

---

iterableapi/src/main/java/com/iterable/iterableapi/AnonymousUserManager.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java

* [MOB-10098](https://iterable.atlassian.net/browse/MOB-10098)
> This pull request updates the user update to be properly passed by as part of the anonymous session. We were not parsing the user update object to pass back the contents of data fields and sending the data fields key along improperly.
[MOB-10098]: https://iterable.atlassian.net/browse/MOB-10098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-10098] updates user update parsing

---

CHANGELOG.md
iterableapi-ui/build.gradle
iterableapi/build.gradle
sample-apps/inbox-customization/app/build.gradle

* [MOB-10116](https://iterable.atlassian.net/browse/MOB-10116)
> This pull request prepares for the AUA beta release.
[MOB-10116]: https://iterable.atlassian.net/browse/MOB-10116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-10116] prepares for 3.6.0-beta release

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableWebViewClient.java

* [MOB-9211](https://iterable.atlassian.net/browse/MOB-9211)
> Removing treeobserver as the html would keep calling this callback even after the page was finished loading. This method was used as an additional measure to make sure inapps are resized in situation when inapps were still not displayed after finished loading. This fix adds delay of 100ms which seems to resolve inapps on Pixel 6pro and still making it all work on Pixel 8 device, needing the SDK to not rely on tree observers.
[MOB-9211]: https://iterable.atlassian.net/browse/MOB-9211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-9211] - InApp resizing fix

---

.github/workflows/build.yml
iterableapi-ui/src/main/java/com/iterable/iterableapi/ui/inbox/IterableInboxFragment.java

* [MOB-9111](https://iterable.atlassian.net/browse/MOB-9111)
> This fix makes the IterableInboxFragment adjust with window insets allowing full screen apps to take advantage of IterableInboxActivity or IterableInboxFragment. As IterableInboxActivity internally launches IterableFragment, the changes in Fragment is sufficient to make up for cut outs and notches on displays
[MOB-9111]: https://iterable.atlassian.net/browse/MOB-9111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-9111] - Inbox overlap on Android 35

---

CHANGELOG.md
iterableapi/build.gradle
iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableConfig.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableDataEncryptor.kt
iterableapi/src/main/java/com/iterable/iterableapi/IterableDecryptionFailureHandler.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableKeychain.kt
iterableapi/src/main/java/com/iterable/iterableapi/IterableKeychainEncryptedDataMigrator.kt
iterableapi/src/test/java/com/iterable/iterableapi/IterableDataEncryptorTest.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableKeychainEncryptedDataMigratorTest.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableKeychainTest.kt

… shared prefs
* [MOB-9235](https://iterable.atlassian.net/browse/MOB-9235)
To prevent ANRs we are migrating data from encrypted to shared prefs and discontinue use of encrypted shared prefs
[MOB-9235]: https://iterable.atlassian.net/browse/MOB-9235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-9235] ANR Prevention by migrating data from encrypted to shared prefs and discontinue use of encrypted shared prefs

---

CHANGELOG.md
iterableapi/src/main/java/com/iterable/iterableapi/IterableDataEncryptor.kt

[MOB-9235] Fix variable IV length issue

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java

* [MOB-9446](https://iterable.atlassian.net/browse/MOB-9446)
> This pull request enhances push notification state tracking. This cherry picks the changes from PR #843 to merge into master branch.
[MOB-9446]: https://iterable.atlassian.net/browse/MOB-9446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-9446] enhance push notification state tracking

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java

* [MOB-9446](https://iterable.atlassian.net/browse/MOB-9446)
[MOB-9446]: https://iterable.atlassian.net/browse/MOB-9446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Logic fix suggestion for Push Notifications

---

CHANGELOG.md
iterableapi-ui/build.gradle
iterableapi/build.gradle
sample-apps/inbox-customization/app/build.gradle
sample-apps/inbox-customization/build.gradle

* [MOB-10610](https://iterable.atlassian.net/browse/MOB-10610)
> This pull request prepares version 6.5.8 release.
[MOB-10610]: https://iterable.atlassian.net/browse/MOB-10610?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-10610] prepares for version 6.5.8 release

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java

* [MOB-10627](https://iterable.atlassian.net/browse/MOB-10627)
> This pull request removes the disable device call from the enhanced notification tracking logic.
[MOB-10627]: https://iterable.atlassian.net/browse/MOB-10627?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-10627] removes disable device call

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedManager.kt
iterableapi/src/test/java/com/iterable/iterableapi/IterableEmbeddedManagerTest.java
iterableapi/src/test/resources/embedded_payload_single_placement_id_0.json
iterableapi/src/test/resources/embedded_payload_single_placement_id_2.json

* [MOB-8301](https://iterable.atlassian.net/browse/MOB-8301)
> This pull request adds optional parameter for placement ids to make use of optional parameter on the API call.
[MOB-8301]: https://iterable.atlassian.net/browse/MOB-8301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-8301] adds optional parameter to syncMessages

---

CHANGELOG.md
iterableapi-ui/build.gradle
iterableapi/build.gradle
sample-apps/inbox-customization/app/build.gradle
sample-apps/inbox-customization/build.gradle

* [MOB-10928](https://iterable.atlassian.net/browse/MOB-10928)
> This pull request prepares for version 3.6.0-beta2 release.
[MOB-10928]: https://iterable.atlassian.net/browse/MOB-10928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-10928] updates changelog and version numbers

---

iterableapi-ui/src/main/java/com/iterable/iterableapi/ui/embedded/IterableEmbeddedView.kt
iterableapi-ui/src/main/res/layout-v21/card_view.xml

* [MOB-8305](https://iterable.atlassian.net/browse/MOB-8305)
> This pull request fixes bug where text container shrinks when buttons are not present.
[MOB-8305]: https://iterable.atlassian.net/browse/MOB-8305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-8305] maintain text container height when buttons are not present

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableKeychain.kt
iterableapi/src/test/java/com/iterable/iterableapi/IterableDataEncryptorTest.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableKeychainTest.kt

Added plaintext fallback for data storage when encryption fails:
- Modified `IterableKeychain` to handle encryption failures gracefully
- Data is stored in plaintext with a flag when encryption fails
- Added unit tests to verify fallback behavior
- Maintains backward compatibility with existing encrypted data
Key changes:
1. Added plaintext flag to track unencrypted data
2. Implemented fallback mechanism in `secureSave`
3. Updated `secureGet` to handle plaintext data
4. Added comprehensive test coverage

MOB-10857 fix encryption crash

---

.github/workflows/publish.yml
maven-push.gradle

Reverting the changes causing release block

---

app/build.gradle
iterableapi-ui/build.gradle

* [MOB-XXXX](https://iterable.atlassian.net/browse/MOB-11168)
> Reverting this change as the obfuscation is preventing us to refer embedded ui files while in staging. And thinking this could affect in release builds as well. Good that we caught this here. In fact all the release should be tested against staging is what I am getting now.

[MOB-11168] - Revert minifyEnabled

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableConfig.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableKeychain.kt
iterableapi/src/test/java/com/iterable/iterableapi/IterableConfigTest.kt
iterableapi/src/test/java/com/iterable/iterableapi/IterableKeychainTest.kt

TOP - UP PR for suggested naming inversion.
@sumeruchat Please check if the Test modification makes sense.

Mob 11167 fix anr renaming config

---

README.md
app/build.gradle
iterableapi/build.gradle
iterableapi/src/test/java/com/iterable/iterableapi/IterablePushActionReceiverTest.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableTestUtils.java

N/A
This PR contains multiple commits to update your usage of Robolectric:
- Remove declarations of `org.robolectric:shadows-playservices`, since it doesn't seem to be needed.
- Replace usages of `RuntimeEnvironment.application` with `ApplicationProvider.getApplicationContext()`. The former is deprecated, and the recommended alternative is either `RuntimeEnvironment.getApplication()` or `ApplicationProvider.getApplicationContext()` (provided by AndroidX Test). I went with the AndroidX Test alternative, as it makes the test less Robolectric-dependent (i.e. it may be run on a device too).
A couple of small fixes were also made in the `README.md` file to use the correct min SDK version and fix the link to the license file.

Update Robolectric usage

---

CHANGELOG.md
iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java

* [MOB-11292](https://iterable.atlassian.net/browse/MOB-11292)
SDK calls getMessages, registerDevice Apis when initializing. When push track happens, initialization also includes push track in the sequence. However, in current sequence, process pending actions which lead to push tracking was done after lifecycle handling was done where getMessages and registerDevice happens.
JWT mechanism only retries the first failed call. Thus push track open would not get retried as the first failing call would be getMessages and that would be retried when JWT failure occurred.
This PR will change the sequence and make sure Push related APIs are first in line so they are retried instead of getMessages. This solution is better than current one as the sequence of api calls will more align with iOS …

[MOB - 11292] - Process Pending Action First

---

iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java
iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java
iterableapi/src/main/java/com/iterable/iterableapi/UnknownUserManager.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableApiAuthTests.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableApiMergeUserEmailTests.java
iterableapi/src/test/java/com/iterable/iterableapi/IterableApiRequestTest.java

* [MOB-11677](https://iterable.atlassian.net/browse/MOB-11677)
* [MOB-11739](https://iterable.atlassian.net/browse/MOB-11739)
This pull request implements the storage of the time of consent and calling a new method, trackConsent, when a user logs in and replays events or an anonymous user is generated. Also addresses bug that prevents unknown user generation when user logs out.
[MOB-11677]: https://iterable.atlassian.net/browse/MOB-11677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOB-11739]: https://iterable.atlassian.net/browse/MOB-11739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-11677] consent logging

---

.editorconfig
.github/workflows/publish.yml
.gitignore
build.gradle
maven-push.gradle

N/A
Migrates Android SDK publishing from legacy OSSRH to the new Sonatype Central publishing system using the NMCP plugin. This includes:
- Updated GitHub Actions workflow to use Sonatype Central authentication
- Configured NMCP plugin for automatic publishing
- Added GPG signing configuration for CI
- Simplified publishing tasks by removing legacy uploadArchives wrapper
The migration maintains backward compatibility while modernizing the publishing infrastructure.

Migrate from OSSRH to Sonatype Central publishing

---

CHANGELOG.md

> Minor update to changelog to point to public beta.

[MOB-XXXX] updates changelog to point out public beta

---

CHANGELOG.md
iterableapi-ui/build.gradle
iterableapi/build.gradle
sample-apps/inbox-customization/app/build.gradle

* [MOB-12181](https://iterable.atlassian.net/browse/MOB-12181)
[MOB-12181]: https://iterable.atlassian.net/browse/MOB-12181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOB-12181] - Prepare for 3.6.1
